// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BindPacket.proto

package cn.starboot.tim.common.packet.proto;

public final class BindPacketProto {
  private BindPacketProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BindPacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BindPacket)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 绑定ID
     * </pre>
     *
     * <code>string bindId = 1;</code>
     * @return The bindId.
     */
    String getBindId();
    /**
     * <pre>
     * 绑定ID
     * </pre>
     *
     * <code>string bindId = 1;</code>
     * @return The bytes for bindId.
     */
    com.google.protobuf.ByteString
        getBindIdBytes();

    /**
     * <pre>
     * bind类型
     * </pre>
     *
     * <code>.BindPacket.BindType bindType = 3;</code>
     * @return The enum numeric value on the wire for bindType.
     */
    int getBindTypeValue();
    /**
     * <pre>
     * bind类型
     * </pre>
     *
     * <code>.BindPacket.BindType bindType = 3;</code>
     * @return The bindType.
     */
    BindPacket.BindType getBindType();

    /**
     * <pre>
     * 绑定、解绑
     * </pre>
     *
     * <code>.BindPacket.OptionType optionType = 4;</code>
     * @return The enum numeric value on the wire for optionType.
     */
    int getOptionTypeValue();
    /**
     * <pre>
     * 绑定、解绑
     * </pre>
     *
     * <code>.BindPacket.OptionType optionType = 4;</code>
     * @return The optionType.
     */
    BindPacket.OptionType getOptionType();
  }
  /**
   * <pre>
   * IM绑定、解绑消息包
   * </pre>
   *
   * Protobuf type {@code BindPacket}
   */
  public static final class BindPacket extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:BindPacket)
      BindPacketOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BindPacket.newBuilder() to construct.
    private BindPacket(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BindPacket() {
      bindId_ = "";
      bindType_ = 0;
      optionType_ = 0;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new BindPacket();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BindPacket(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              bindId_ = s;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              bindType_ = rawValue;
              break;
            }
            case 32: {
              int rawValue = input.readEnum();

              optionType_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BindPacketProto.internal_static_BindPacket_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BindPacketProto.internal_static_BindPacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              BindPacket.class, Builder.class);
    }

    /**
     * Protobuf enum {@code BindPacket.BindType}
     */
    public enum BindType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       * 绑定用户（可以解除或者绑定用户的某一设备）
       * </pre>
       *
       * <code>USER = 0;</code>
       */
      USER(0),
      /**
       * <pre>
       * 绑定群组
       * </pre>
       *
       * <code>GROUP = 1;</code>
       */
      GROUP(1),
      /**
       * <pre>
       * 绑定token
       * </pre>
       *
       * <code>TOKEN = 2;</code>
       */
      TOKEN(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <pre>
       * 绑定用户（可以解除或者绑定用户的某一设备）
       * </pre>
       *
       * <code>USER = 0;</code>
       */
      public static final int USER_VALUE = 0;
      /**
       * <pre>
       * 绑定群组
       * </pre>
       *
       * <code>GROUP = 1;</code>
       */
      public static final int GROUP_VALUE = 1;
      /**
       * <pre>
       * 绑定token
       * </pre>
       *
       * <code>TOKEN = 2;</code>
       */
      public static final int TOKEN_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static BindType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static BindType forNumber(int value) {
        switch (value) {
          case 0: return USER;
          case 1: return GROUP;
          case 2: return TOKEN;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<BindType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          BindType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<BindType>() {
              public BindType findValueByNumber(int number) {
                return BindType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return BindPacket.getDescriptor().getEnumTypes().get(0);
      }

      private static final BindType[] VALUES = values();

      public static BindType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private BindType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:BindPacket.BindType)
    }

    /**
     * Protobuf enum {@code BindPacket.OptionType}
     */
    public enum OptionType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       * 绑定
       * </pre>
       *
       * <code>BIND = 0;</code>
       */
      BIND(0),
      /**
       * <pre>
       * 解绑
       * </pre>
       *
       * <code>UNBIND = 1;</code>
       */
      UNBIND(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <pre>
       * 绑定
       * </pre>
       *
       * <code>BIND = 0;</code>
       */
      public static final int BIND_VALUE = 0;
      /**
       * <pre>
       * 解绑
       * </pre>
       *
       * <code>UNBIND = 1;</code>
       */
      public static final int UNBIND_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static OptionType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static OptionType forNumber(int value) {
        switch (value) {
          case 0: return BIND;
          case 1: return UNBIND;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<OptionType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          OptionType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<OptionType>() {
              public OptionType findValueByNumber(int number) {
                return OptionType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return BindPacket.getDescriptor().getEnumTypes().get(1);
      }

      private static final OptionType[] VALUES = values();

      public static OptionType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private OptionType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:BindPacket.OptionType)
    }

    public static final int BINDID_FIELD_NUMBER = 1;
    private volatile Object bindId_;
    /**
     * <pre>
     * 绑定ID
     * </pre>
     *
     * <code>string bindId = 1;</code>
     * @return The bindId.
     */
    @Override
    public String getBindId() {
      Object ref = bindId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        bindId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 绑定ID
     * </pre>
     *
     * <code>string bindId = 1;</code>
     * @return The bytes for bindId.
     */
    @Override
    public com.google.protobuf.ByteString
        getBindIdBytes() {
      Object ref = bindId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        bindId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BINDTYPE_FIELD_NUMBER = 3;
    private int bindType_;
    /**
     * <pre>
     * bind类型
     * </pre>
     *
     * <code>.BindPacket.BindType bindType = 3;</code>
     * @return The enum numeric value on the wire for bindType.
     */
    @Override public int getBindTypeValue() {
      return bindType_;
    }
    /**
     * <pre>
     * bind类型
     * </pre>
     *
     * <code>.BindPacket.BindType bindType = 3;</code>
     * @return The bindType.
     */
    @Override public BindType getBindType() {
      @SuppressWarnings("deprecation")
      BindType result = BindType.valueOf(bindType_);
      return result == null ? BindType.UNRECOGNIZED : result;
    }

    public static final int OPTIONTYPE_FIELD_NUMBER = 4;
    private int optionType_;
    /**
     * <pre>
     * 绑定、解绑
     * </pre>
     *
     * <code>.BindPacket.OptionType optionType = 4;</code>
     * @return The enum numeric value on the wire for optionType.
     */
    @Override public int getOptionTypeValue() {
      return optionType_;
    }
    /**
     * <pre>
     * 绑定、解绑
     * </pre>
     *
     * <code>.BindPacket.OptionType optionType = 4;</code>
     * @return The optionType.
     */
    @Override public OptionType getOptionType() {
      @SuppressWarnings("deprecation")
      OptionType result = OptionType.valueOf(optionType_);
      return result == null ? OptionType.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(bindId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, bindId_);
      }
      if (bindType_ != BindType.USER.getNumber()) {
        output.writeEnum(3, bindType_);
      }
      if (optionType_ != OptionType.BIND.getNumber()) {
        output.writeEnum(4, optionType_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(bindId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, bindId_);
      }
      if (bindType_ != BindType.USER.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, bindType_);
      }
      if (optionType_ != OptionType.BIND.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, optionType_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof BindPacket)) {
        return super.equals(obj);
      }
      BindPacket other = (BindPacket) obj;

      if (!getBindId()
          .equals(other.getBindId())) return false;
      if (bindType_ != other.bindType_) return false;
      if (optionType_ != other.optionType_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BINDID_FIELD_NUMBER;
      hash = (53 * hash) + getBindId().hashCode();
      hash = (37 * hash) + BINDTYPE_FIELD_NUMBER;
      hash = (53 * hash) + bindType_;
      hash = (37 * hash) + OPTIONTYPE_FIELD_NUMBER;
      hash = (53 * hash) + optionType_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static BindPacket parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BindPacket parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BindPacket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BindPacket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BindPacket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BindPacket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BindPacket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static BindPacket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static BindPacket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static BindPacket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static BindPacket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static BindPacket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(BindPacket prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * IM绑定、解绑消息包
     * </pre>
     *
     * Protobuf type {@code BindPacket}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BindPacket)
        BindPacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return BindPacketProto.internal_static_BindPacket_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return BindPacketProto.internal_static_BindPacket_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                BindPacket.class, Builder.class);
      }

      // Construct using cn.starboot.tim.common.packet.proto.BindPacketProto.BindPacket.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        bindId_ = "";

        bindType_ = 0;

        optionType_ = 0;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return BindPacketProto.internal_static_BindPacket_descriptor;
      }

      @Override
      public BindPacket getDefaultInstanceForType() {
        return BindPacket.getDefaultInstance();
      }

      @Override
      public BindPacket build() {
        BindPacket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public BindPacket buildPartial() {
        BindPacket result = new BindPacket(this);
        result.bindId_ = bindId_;
        result.bindType_ = bindType_;
        result.optionType_ = optionType_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof BindPacket) {
          return mergeFrom((BindPacket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(BindPacket other) {
        if (other == BindPacket.getDefaultInstance()) return this;
        if (!other.getBindId().isEmpty()) {
          bindId_ = other.bindId_;
          onChanged();
        }
        if (other.bindType_ != 0) {
          setBindTypeValue(other.getBindTypeValue());
        }
        if (other.optionType_ != 0) {
          setOptionTypeValue(other.getOptionTypeValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        BindPacket parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (BindPacket) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object bindId_ = "";
      /**
       * <pre>
       * 绑定ID
       * </pre>
       *
       * <code>string bindId = 1;</code>
       * @return The bindId.
       */
      public String getBindId() {
        Object ref = bindId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          bindId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 绑定ID
       * </pre>
       *
       * <code>string bindId = 1;</code>
       * @return The bytes for bindId.
       */
      public com.google.protobuf.ByteString
          getBindIdBytes() {
        Object ref = bindId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          bindId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 绑定ID
       * </pre>
       *
       * <code>string bindId = 1;</code>
       * @param value The bindId to set.
       * @return This builder for chaining.
       */
      public Builder setBindId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        bindId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 绑定ID
       * </pre>
       *
       * <code>string bindId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearBindId() {
        
        bindId_ = getDefaultInstance().getBindId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 绑定ID
       * </pre>
       *
       * <code>string bindId = 1;</code>
       * @param value The bytes for bindId to set.
       * @return This builder for chaining.
       */
      public Builder setBindIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        bindId_ = value;
        onChanged();
        return this;
      }

      private int bindType_ = 0;
      /**
       * <pre>
       * bind类型
       * </pre>
       *
       * <code>.BindPacket.BindType bindType = 3;</code>
       * @return The enum numeric value on the wire for bindType.
       */
      @Override public int getBindTypeValue() {
        return bindType_;
      }
      /**
       * <pre>
       * bind类型
       * </pre>
       *
       * <code>.BindPacket.BindType bindType = 3;</code>
       * @param value The enum numeric value on the wire for bindType to set.
       * @return This builder for chaining.
       */
      public Builder setBindTypeValue(int value) {
        
        bindType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * bind类型
       * </pre>
       *
       * <code>.BindPacket.BindType bindType = 3;</code>
       * @return The bindType.
       */
      @Override
      public BindType getBindType() {
        @SuppressWarnings("deprecation")
        BindType result = BindType.valueOf(bindType_);
        return result == null ? BindType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * bind类型
       * </pre>
       *
       * <code>.BindPacket.BindType bindType = 3;</code>
       * @param value The bindType to set.
       * @return This builder for chaining.
       */
      public Builder setBindType(BindType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        bindType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * bind类型
       * </pre>
       *
       * <code>.BindPacket.BindType bindType = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearBindType() {
        
        bindType_ = 0;
        onChanged();
        return this;
      }

      private int optionType_ = 0;
      /**
       * <pre>
       * 绑定、解绑
       * </pre>
       *
       * <code>.BindPacket.OptionType optionType = 4;</code>
       * @return The enum numeric value on the wire for optionType.
       */
      @Override public int getOptionTypeValue() {
        return optionType_;
      }
      /**
       * <pre>
       * 绑定、解绑
       * </pre>
       *
       * <code>.BindPacket.OptionType optionType = 4;</code>
       * @param value The enum numeric value on the wire for optionType to set.
       * @return This builder for chaining.
       */
      public Builder setOptionTypeValue(int value) {
        
        optionType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 绑定、解绑
       * </pre>
       *
       * <code>.BindPacket.OptionType optionType = 4;</code>
       * @return The optionType.
       */
      @Override
      public OptionType getOptionType() {
        @SuppressWarnings("deprecation")
        OptionType result = OptionType.valueOf(optionType_);
        return result == null ? OptionType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * 绑定、解绑
       * </pre>
       *
       * <code>.BindPacket.OptionType optionType = 4;</code>
       * @param value The optionType to set.
       * @return This builder for chaining.
       */
      public Builder setOptionType(OptionType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        optionType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 绑定、解绑
       * </pre>
       *
       * <code>.BindPacket.OptionType optionType = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearOptionType() {
        
        optionType_ = 0;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:BindPacket)
    }

    // @@protoc_insertion_point(class_scope:BindPacket)
    private static final BindPacket DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new BindPacket();
    }

    public static BindPacket getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BindPacket>
        PARSER = new com.google.protobuf.AbstractParser<BindPacket>() {
      @Override
      public BindPacket parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BindPacket(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BindPacket> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<BindPacket> getParserForType() {
      return PARSER;
    }

    @Override
    public BindPacket getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BindPacket_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BindPacket_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020BindPacket.proto\"\300\001\n\nBindPacket\022\016\n\006bin" +
      "dId\030\001 \001(\t\022&\n\010bindType\030\003 \001(\0162\024.BindPacket" +
      ".BindType\022*\n\noptionType\030\004 \001(\0162\026.BindPack" +
      "et.OptionType\"*\n\010BindType\022\010\n\004USER\020\000\022\t\n\005G" +
      "ROUP\020\001\022\t\n\005TOKEN\020\002\"\"\n\nOptionType\022\010\n\004BIND\020" +
      "\000\022\n\n\006UNBIND\020\001B6\n#cn.starboot.tim.common." +
      "packet.protoB\017BindPacketProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_BindPacket_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_BindPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BindPacket_descriptor,
        new String[] { "BindId", "BindType", "OptionType", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
