// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChatPacket.proto

package cn.starboot.tim.common.packet.proto;

public final class ChatPacketProto {
  private ChatPacketProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ChatPacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.ChatPacket)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 发送者ID
     * </pre>
     *
     * <code>string fromId = 1;</code>
     * @return The fromId.
     */
    String getFromId();
    /**
     * <pre>
     * 发送者ID
     * </pre>
     *
     * <code>string fromId = 1;</code>
     * @return The bytes for fromId.
     */
    com.google.protobuf.ByteString
        getFromIdBytes();

    /**
     * <pre>
     * 接收者ID
     * </pre>
     *
     * <code>string toId = 2;</code>
     * @return The toId.
     */
    String getToId();
    /**
     * <pre>
     * 接收者ID
     * </pre>
     *
     * <code>string toId = 2;</code>
     * @return The bytes for toId.
     */
    com.google.protobuf.ByteString
        getToIdBytes();

    /**
     * <pre>
     * 消息创建时间
     * </pre>
     *
     * <code>int64 createTime = 3;</code>
     * @return The createTime.
     */
    long getCreateTime();

    /**
     * <code>.proto.ChatPacket.MsgType msgType = 4;</code>
     * @return The enum numeric value on the wire for msgType.
     */
    int getMsgTypeValue();
    /**
     * <code>.proto.ChatPacket.MsgType msgType = 4;</code>
     * @return The msgType.
     */
    ChatPacket.MsgType getMsgType();

    /**
     * <code>.proto.ChatPacket.ChatType chatType = 5;</code>
     * @return The enum numeric value on the wire for chatType.
     */
    int getChatTypeValue();
    /**
     * <code>.proto.ChatPacket.ChatType chatType = 5;</code>
     * @return The chatType.
     */
    ChatPacket.ChatType getChatType();

    /**
     * <pre>
     * 消息内容
     * </pre>
     *
     * <code>string content = 6;</code>
     * @return The content.
     */
    String getContent();
    /**
     * <pre>
     * 消息内容
     * </pre>
     *
     * <code>string content = 6;</code>
     * @return The bytes for content.
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <pre>
     * 群组ID
     * </pre>
     *
     * <code>string groupId = 7;</code>
     * @return The groupId.
     */
    String getGroupId();
    /**
     * <pre>
     * 群组ID
     * </pre>
     *
     * <code>string groupId = 7;</code>
     * @return The bytes for groupId.
     */
    com.google.protobuf.ByteString
        getGroupIdBytes();

    /**
     * <pre>
     * 扩展字段,JSON对象格式如：{'扩展字段名称':'扩展字段value'}
     * </pre>
     *
     * <code>string extras = 8;</code>
     * @return The extras.
     */
    String getExtras();
    /**
     * <pre>
     * 扩展字段,JSON对象格式如：{'扩展字段名称':'扩展字段value'}
     * </pre>
     *
     * <code>string extras = 8;</code>
     * @return The bytes for extras.
     */
    com.google.protobuf.ByteString
        getExtrasBytes();
  }
  /**
   * <pre>
   *"from": "来源ID",
   *"to": "目标ID",
   *"createTime": "消息创建时间long类型",
   *"msgType": "消息类型int类型(0:text、1:image、2:voice、3:video、4:music、5:news、6:语音通话、7:视频通话、8:视频会议)",
   *"chatType":"聊天类型int类型(0:未知,1:公聊,2:私聊)",
   *"groupId":"群组id仅在chatType为(1)时需要,String类型",
   *"content": "内容",
   *"extras" : "扩展字段,JSON对象格式如：{'扩展字段名称':'扩展字段value'}"
   * </pre>
   *
   * Protobuf type {@code proto.ChatPacket}
   */
  public static final class ChatPacket extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.ChatPacket)
      ChatPacketOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ChatPacket.newBuilder() to construct.
    private ChatPacket(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ChatPacket() {
      fromId_ = "";
      toId_ = "";
      msgType_ = 0;
      chatType_ = 0;
      content_ = "";
      groupId_ = "";
      extras_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new ChatPacket();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ChatPacket(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              fromId_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              toId_ = s;
              break;
            }
            case 24: {

              createTime_ = input.readInt64();
              break;
            }
            case 32: {
              int rawValue = input.readEnum();

              msgType_ = rawValue;
              break;
            }
            case 40: {
              int rawValue = input.readEnum();

              chatType_ = rawValue;
              break;
            }
            case 50: {
              String s = input.readStringRequireUtf8();

              content_ = s;
              break;
            }
            case 58: {
              String s = input.readStringRequireUtf8();

              groupId_ = s;
              break;
            }
            case 66: {
              String s = input.readStringRequireUtf8();

              extras_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ChatPacketProto.internal_static_proto_ChatPacket_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ChatPacketProto.internal_static_proto_ChatPacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ChatPacket.class, Builder.class);
    }

    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * Protobuf enum {@code proto.ChatPacket.MsgType}
     */
    public enum MsgType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       * 文本消息
       * </pre>
       *
       * <code>TEXT = 0;</code>
       */
      TEXT(0),
      /**
       * <pre>
       * 图片消息
       * </pre>
       *
       * <code>IMAGE = 1;</code>
       */
      IMAGE(1),
      /**
       * <pre>
       * 语音消息
       * </pre>
       *
       * <code>VOICE = 2;</code>
       */
      VOICE(2),
      /**
       * <pre>
       * 视频消息
       * </pre>
       *
       * <code>VIDEO = 3;</code>
       */
      VIDEO(3),
      /**
       * <pre>
       * 音乐消息
       * </pre>
       *
       * <code>MUSIC = 4;</code>
       */
      MUSIC(4),
      /**
       * <pre>
       * 新闻消息
       * </pre>
       *
       * <code>NEWS = 5;</code>
       */
      NEWS(5),
      /**
       * <pre>
       * 语音通话
       * </pre>
       *
       * <code>ONLINE_VOICE = 6;</code>
       */
      ONLINE_VOICE(6),
      /**
       * <pre>
       * 视频通话
       * </pre>
       *
       * <code>ONLINE_VIDEO = 7;</code>
       */
      ONLINE_VIDEO(7),
      /**
       * <pre>
       * 视频会议
       * </pre>
       *
       * <code>ONLINE_MEETING = 8;</code>
       */
      ONLINE_MEETING(8),
      UNRECOGNIZED(-1),
      ;

      /**
       * <pre>
       * 文本消息
       * </pre>
       *
       * <code>TEXT = 0;</code>
       */
      public static final int TEXT_VALUE = 0;
      /**
       * <pre>
       * 图片消息
       * </pre>
       *
       * <code>IMAGE = 1;</code>
       */
      public static final int IMAGE_VALUE = 1;
      /**
       * <pre>
       * 语音消息
       * </pre>
       *
       * <code>VOICE = 2;</code>
       */
      public static final int VOICE_VALUE = 2;
      /**
       * <pre>
       * 视频消息
       * </pre>
       *
       * <code>VIDEO = 3;</code>
       */
      public static final int VIDEO_VALUE = 3;
      /**
       * <pre>
       * 音乐消息
       * </pre>
       *
       * <code>MUSIC = 4;</code>
       */
      public static final int MUSIC_VALUE = 4;
      /**
       * <pre>
       * 新闻消息
       * </pre>
       *
       * <code>NEWS = 5;</code>
       */
      public static final int NEWS_VALUE = 5;
      /**
       * <pre>
       * 语音通话
       * </pre>
       *
       * <code>ONLINE_VOICE = 6;</code>
       */
      public static final int ONLINE_VOICE_VALUE = 6;
      /**
       * <pre>
       * 视频通话
       * </pre>
       *
       * <code>ONLINE_VIDEO = 7;</code>
       */
      public static final int ONLINE_VIDEO_VALUE = 7;
      /**
       * <pre>
       * 视频会议
       * </pre>
       *
       * <code>ONLINE_MEETING = 8;</code>
       */
      public static final int ONLINE_MEETING_VALUE = 8;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static MsgType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static MsgType forNumber(int value) {
        switch (value) {
          case 0: return TEXT;
          case 1: return IMAGE;
          case 2: return VOICE;
          case 3: return VIDEO;
          case 4: return MUSIC;
          case 5: return NEWS;
          case 6: return ONLINE_VOICE;
          case 7: return ONLINE_VIDEO;
          case 8: return ONLINE_MEETING;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MsgType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          MsgType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MsgType>() {
              public MsgType findValueByNumber(int number) {
                return MsgType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return ChatPacket.getDescriptor().getEnumTypes().get(0);
      }

      private static final MsgType[] VALUES = values();

      public static MsgType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private MsgType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:proto.ChatPacket.MsgType)
    }

    /**
     * <pre>
     * 聊天类型
     * </pre>
     *
     * Protobuf enum {@code proto.ChatPacket.ChatType}
     */
    public enum ChatType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       * 未知消息
       * </pre>
       *
       * <code>UNKNOWN = 0;</code>
       */
      UNKNOWN(0),
      /**
       * <pre>
       * 群聊消息
       * </pre>
       *
       * <code>GROUP = 1;</code>
       */
      GROUP(1),
      /**
       * <pre>
       * 私聊消息
       * </pre>
       *
       * <code>PRIVATE = 2;</code>
       */
      PRIVATE(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <pre>
       * 未知消息
       * </pre>
       *
       * <code>UNKNOWN = 0;</code>
       */
      public static final int UNKNOWN_VALUE = 0;
      /**
       * <pre>
       * 群聊消息
       * </pre>
       *
       * <code>GROUP = 1;</code>
       */
      public static final int GROUP_VALUE = 1;
      /**
       * <pre>
       * 私聊消息
       * </pre>
       *
       * <code>PRIVATE = 2;</code>
       */
      public static final int PRIVATE_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static ChatType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static ChatType forNumber(int value) {
        switch (value) {
          case 0: return UNKNOWN;
          case 1: return GROUP;
          case 2: return PRIVATE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ChatType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          ChatType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ChatType>() {
              public ChatType findValueByNumber(int number) {
                return ChatType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return ChatPacket.getDescriptor().getEnumTypes().get(1);
      }

      private static final ChatType[] VALUES = values();

      public static ChatType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private ChatType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:proto.ChatPacket.ChatType)
    }

    public static final int FROMID_FIELD_NUMBER = 1;
    private volatile Object fromId_;
    /**
     * <pre>
     * 发送者ID
     * </pre>
     *
     * <code>string fromId = 1;</code>
     * @return The fromId.
     */
    @Override
    public String getFromId() {
      Object ref = fromId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        fromId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 发送者ID
     * </pre>
     *
     * <code>string fromId = 1;</code>
     * @return The bytes for fromId.
     */
    @Override
    public com.google.protobuf.ByteString
        getFromIdBytes() {
      Object ref = fromId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        fromId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOID_FIELD_NUMBER = 2;
    private volatile Object toId_;
    /**
     * <pre>
     * 接收者ID
     * </pre>
     *
     * <code>string toId = 2;</code>
     * @return The toId.
     */
    @Override
    public String getToId() {
      Object ref = toId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        toId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 接收者ID
     * </pre>
     *
     * <code>string toId = 2;</code>
     * @return The bytes for toId.
     */
    @Override
    public com.google.protobuf.ByteString
        getToIdBytes() {
      Object ref = toId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        toId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CREATETIME_FIELD_NUMBER = 3;
    private long createTime_;
    /**
     * <pre>
     * 消息创建时间
     * </pre>
     *
     * <code>int64 createTime = 3;</code>
     * @return The createTime.
     */
    @Override
    public long getCreateTime() {
      return createTime_;
    }

    public static final int MSGTYPE_FIELD_NUMBER = 4;
    private int msgType_;
    /**
     * <code>.proto.ChatPacket.MsgType msgType = 4;</code>
     * @return The enum numeric value on the wire for msgType.
     */
    @Override public int getMsgTypeValue() {
      return msgType_;
    }
    /**
     * <code>.proto.ChatPacket.MsgType msgType = 4;</code>
     * @return The msgType.
     */
    @Override public MsgType getMsgType() {
      @SuppressWarnings("deprecation")
      MsgType result = MsgType.valueOf(msgType_);
      return result == null ? MsgType.UNRECOGNIZED : result;
    }

    public static final int CHATTYPE_FIELD_NUMBER = 5;
    private int chatType_;
    /**
     * <code>.proto.ChatPacket.ChatType chatType = 5;</code>
     * @return The enum numeric value on the wire for chatType.
     */
    @Override public int getChatTypeValue() {
      return chatType_;
    }
    /**
     * <code>.proto.ChatPacket.ChatType chatType = 5;</code>
     * @return The chatType.
     */
    @Override public ChatType getChatType() {
      @SuppressWarnings("deprecation")
      ChatType result = ChatType.valueOf(chatType_);
      return result == null ? ChatType.UNRECOGNIZED : result;
    }

    public static final int CONTENT_FIELD_NUMBER = 6;
    private volatile Object content_;
    /**
     * <pre>
     * 消息内容
     * </pre>
     *
     * <code>string content = 6;</code>
     * @return The content.
     */
    @Override
    public String getContent() {
      Object ref = content_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 消息内容
     * </pre>
     *
     * <code>string content = 6;</code>
     * @return The bytes for content.
     */
    @Override
    public com.google.protobuf.ByteString
        getContentBytes() {
      Object ref = content_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GROUPID_FIELD_NUMBER = 7;
    private volatile Object groupId_;
    /**
     * <pre>
     * 群组ID
     * </pre>
     *
     * <code>string groupId = 7;</code>
     * @return The groupId.
     */
    @Override
    public String getGroupId() {
      Object ref = groupId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        groupId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 群组ID
     * </pre>
     *
     * <code>string groupId = 7;</code>
     * @return The bytes for groupId.
     */
    @Override
    public com.google.protobuf.ByteString
        getGroupIdBytes() {
      Object ref = groupId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        groupId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXTRAS_FIELD_NUMBER = 8;
    private volatile Object extras_;
    /**
     * <pre>
     * 扩展字段,JSON对象格式如：{'扩展字段名称':'扩展字段value'}
     * </pre>
     *
     * <code>string extras = 8;</code>
     * @return The extras.
     */
    @Override
    public String getExtras() {
      Object ref = extras_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        extras_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 扩展字段,JSON对象格式如：{'扩展字段名称':'扩展字段value'}
     * </pre>
     *
     * <code>string extras = 8;</code>
     * @return The bytes for extras.
     */
    @Override
    public com.google.protobuf.ByteString
        getExtrasBytes() {
      Object ref = extras_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        extras_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fromId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, fromId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(toId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, toId_);
      }
      if (createTime_ != 0L) {
        output.writeInt64(3, createTime_);
      }
      if (msgType_ != MsgType.TEXT.getNumber()) {
        output.writeEnum(4, msgType_);
      }
      if (chatType_ != ChatType.UNKNOWN.getNumber()) {
        output.writeEnum(5, chatType_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(content_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, content_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(groupId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, groupId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(extras_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, extras_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fromId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, fromId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(toId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, toId_);
      }
      if (createTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, createTime_);
      }
      if (msgType_ != MsgType.TEXT.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, msgType_);
      }
      if (chatType_ != ChatType.UNKNOWN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, chatType_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(content_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, content_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(groupId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, groupId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(extras_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, extras_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ChatPacket)) {
        return super.equals(obj);
      }
      ChatPacket other = (ChatPacket) obj;

      if (!getFromId()
          .equals(other.getFromId())) return false;
      if (!getToId()
          .equals(other.getToId())) return false;
      if (getCreateTime()
          != other.getCreateTime()) return false;
      if (msgType_ != other.msgType_) return false;
      if (chatType_ != other.chatType_) return false;
      if (!getContent()
          .equals(other.getContent())) return false;
      if (!getGroupId()
          .equals(other.getGroupId())) return false;
      if (!getExtras()
          .equals(other.getExtras())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FROMID_FIELD_NUMBER;
      hash = (53 * hash) + getFromId().hashCode();
      hash = (37 * hash) + TOID_FIELD_NUMBER;
      hash = (53 * hash) + getToId().hashCode();
      hash = (37 * hash) + CREATETIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCreateTime());
      hash = (37 * hash) + MSGTYPE_FIELD_NUMBER;
      hash = (53 * hash) + msgType_;
      hash = (37 * hash) + CHATTYPE_FIELD_NUMBER;
      hash = (53 * hash) + chatType_;
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (37 * hash) + GROUPID_FIELD_NUMBER;
      hash = (53 * hash) + getGroupId().hashCode();
      hash = (37 * hash) + EXTRAS_FIELD_NUMBER;
      hash = (53 * hash) + getExtras().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ChatPacket parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ChatPacket parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ChatPacket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ChatPacket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ChatPacket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ChatPacket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ChatPacket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ChatPacket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ChatPacket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ChatPacket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ChatPacket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ChatPacket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ChatPacket prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *"from": "来源ID",
     *"to": "目标ID",
     *"createTime": "消息创建时间long类型",
     *"msgType": "消息类型int类型(0:text、1:image、2:voice、3:video、4:music、5:news、6:语音通话、7:视频通话、8:视频会议)",
     *"chatType":"聊天类型int类型(0:未知,1:公聊,2:私聊)",
     *"groupId":"群组id仅在chatType为(1)时需要,String类型",
     *"content": "内容",
     *"extras" : "扩展字段,JSON对象格式如：{'扩展字段名称':'扩展字段value'}"
     * </pre>
     *
     * Protobuf type {@code proto.ChatPacket}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.ChatPacket)
        ChatPacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ChatPacketProto.internal_static_proto_ChatPacket_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ChatPacketProto.internal_static_proto_ChatPacket_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ChatPacket.class, Builder.class);
      }

      // Construct using cn.starboot.tim.common.packet.proto.ChatPacketProto.ChatPacket.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        fromId_ = "";

        toId_ = "";

        createTime_ = 0L;

        msgType_ = 0;

        chatType_ = 0;

        content_ = "";

        groupId_ = "";

        extras_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ChatPacketProto.internal_static_proto_ChatPacket_descriptor;
      }

      @Override
      public ChatPacket getDefaultInstanceForType() {
        return ChatPacket.getDefaultInstance();
      }

      @Override
      public ChatPacket build() {
        ChatPacket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public ChatPacket buildPartial() {
        ChatPacket result = new ChatPacket(this);
        result.fromId_ = fromId_;
        result.toId_ = toId_;
        result.createTime_ = createTime_;
        result.msgType_ = msgType_;
        result.chatType_ = chatType_;
        result.content_ = content_;
        result.groupId_ = groupId_;
        result.extras_ = extras_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ChatPacket) {
          return mergeFrom((ChatPacket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ChatPacket other) {
        if (other == ChatPacket.getDefaultInstance()) return this;
        if (!other.getFromId().isEmpty()) {
          fromId_ = other.fromId_;
          onChanged();
        }
        if (!other.getToId().isEmpty()) {
          toId_ = other.toId_;
          onChanged();
        }
        if (other.getCreateTime() != 0L) {
          setCreateTime(other.getCreateTime());
        }
        if (other.msgType_ != 0) {
          setMsgTypeValue(other.getMsgTypeValue());
        }
        if (other.chatType_ != 0) {
          setChatTypeValue(other.getChatTypeValue());
        }
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          onChanged();
        }
        if (!other.getGroupId().isEmpty()) {
          groupId_ = other.groupId_;
          onChanged();
        }
        if (!other.getExtras().isEmpty()) {
          extras_ = other.extras_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ChatPacket parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ChatPacket) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object fromId_ = "";
      /**
       * <pre>
       * 发送者ID
       * </pre>
       *
       * <code>string fromId = 1;</code>
       * @return The fromId.
       */
      public String getFromId() {
        Object ref = fromId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          fromId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 发送者ID
       * </pre>
       *
       * <code>string fromId = 1;</code>
       * @return The bytes for fromId.
       */
      public com.google.protobuf.ByteString
          getFromIdBytes() {
        Object ref = fromId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          fromId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 发送者ID
       * </pre>
       *
       * <code>string fromId = 1;</code>
       * @param value The fromId to set.
       * @return This builder for chaining.
       */
      public Builder setFromId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        fromId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 发送者ID
       * </pre>
       *
       * <code>string fromId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFromId() {
        
        fromId_ = getDefaultInstance().getFromId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 发送者ID
       * </pre>
       *
       * <code>string fromId = 1;</code>
       * @param value The bytes for fromId to set.
       * @return This builder for chaining.
       */
      public Builder setFromIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        fromId_ = value;
        onChanged();
        return this;
      }

      private Object toId_ = "";
      /**
       * <pre>
       * 接收者ID
       * </pre>
       *
       * <code>string toId = 2;</code>
       * @return The toId.
       */
      public String getToId() {
        Object ref = toId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          toId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 接收者ID
       * </pre>
       *
       * <code>string toId = 2;</code>
       * @return The bytes for toId.
       */
      public com.google.protobuf.ByteString
          getToIdBytes() {
        Object ref = toId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          toId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 接收者ID
       * </pre>
       *
       * <code>string toId = 2;</code>
       * @param value The toId to set.
       * @return This builder for chaining.
       */
      public Builder setToId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        toId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 接收者ID
       * </pre>
       *
       * <code>string toId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearToId() {
        
        toId_ = getDefaultInstance().getToId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 接收者ID
       * </pre>
       *
       * <code>string toId = 2;</code>
       * @param value The bytes for toId to set.
       * @return This builder for chaining.
       */
      public Builder setToIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        toId_ = value;
        onChanged();
        return this;
      }

      private long createTime_ ;
      /**
       * <pre>
       * 消息创建时间
       * </pre>
       *
       * <code>int64 createTime = 3;</code>
       * @return The createTime.
       */
      @Override
      public long getCreateTime() {
        return createTime_;
      }
      /**
       * <pre>
       * 消息创建时间
       * </pre>
       *
       * <code>int64 createTime = 3;</code>
       * @param value The createTime to set.
       * @return This builder for chaining.
       */
      public Builder setCreateTime(long value) {
        
        createTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息创建时间
       * </pre>
       *
       * <code>int64 createTime = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearCreateTime() {
        
        createTime_ = 0L;
        onChanged();
        return this;
      }

      private int msgType_ = 0;
      /**
       * <code>.proto.ChatPacket.MsgType msgType = 4;</code>
       * @return The enum numeric value on the wire for msgType.
       */
      @Override public int getMsgTypeValue() {
        return msgType_;
      }
      /**
       * <code>.proto.ChatPacket.MsgType msgType = 4;</code>
       * @param value The enum numeric value on the wire for msgType to set.
       * @return This builder for chaining.
       */
      public Builder setMsgTypeValue(int value) {
        
        msgType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.proto.ChatPacket.MsgType msgType = 4;</code>
       * @return The msgType.
       */
      @Override
      public MsgType getMsgType() {
        @SuppressWarnings("deprecation")
        MsgType result = MsgType.valueOf(msgType_);
        return result == null ? MsgType.UNRECOGNIZED : result;
      }
      /**
       * <code>.proto.ChatPacket.MsgType msgType = 4;</code>
       * @param value The msgType to set.
       * @return This builder for chaining.
       */
      public Builder setMsgType(MsgType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        msgType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.proto.ChatPacket.MsgType msgType = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgType() {
        
        msgType_ = 0;
        onChanged();
        return this;
      }

      private int chatType_ = 0;
      /**
       * <code>.proto.ChatPacket.ChatType chatType = 5;</code>
       * @return The enum numeric value on the wire for chatType.
       */
      @Override public int getChatTypeValue() {
        return chatType_;
      }
      /**
       * <code>.proto.ChatPacket.ChatType chatType = 5;</code>
       * @param value The enum numeric value on the wire for chatType to set.
       * @return This builder for chaining.
       */
      public Builder setChatTypeValue(int value) {
        
        chatType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.proto.ChatPacket.ChatType chatType = 5;</code>
       * @return The chatType.
       */
      @Override
      public ChatType getChatType() {
        @SuppressWarnings("deprecation")
        ChatType result = ChatType.valueOf(chatType_);
        return result == null ? ChatType.UNRECOGNIZED : result;
      }
      /**
       * <code>.proto.ChatPacket.ChatType chatType = 5;</code>
       * @param value The chatType to set.
       * @return This builder for chaining.
       */
      public Builder setChatType(ChatType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        chatType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.proto.ChatPacket.ChatType chatType = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearChatType() {
        
        chatType_ = 0;
        onChanged();
        return this;
      }

      private Object content_ = "";
      /**
       * <pre>
       * 消息内容
       * </pre>
       *
       * <code>string content = 6;</code>
       * @return The content.
       */
      public String getContent() {
        Object ref = content_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 消息内容
       * </pre>
       *
       * <code>string content = 6;</code>
       * @return The bytes for content.
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 消息内容
       * </pre>
       *
       * <code>string content = 6;</code>
       * @param value The content to set.
       * @return This builder for chaining.
       */
      public Builder setContent(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息内容
       * </pre>
       *
       * <code>string content = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息内容
       * </pre>
       *
       * <code>string content = 6;</code>
       * @param value The bytes for content to set.
       * @return This builder for chaining.
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        content_ = value;
        onChanged();
        return this;
      }

      private Object groupId_ = "";
      /**
       * <pre>
       * 群组ID
       * </pre>
       *
       * <code>string groupId = 7;</code>
       * @return The groupId.
       */
      public String getGroupId() {
        Object ref = groupId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          groupId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 群组ID
       * </pre>
       *
       * <code>string groupId = 7;</code>
       * @return The bytes for groupId.
       */
      public com.google.protobuf.ByteString
          getGroupIdBytes() {
        Object ref = groupId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          groupId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 群组ID
       * </pre>
       *
       * <code>string groupId = 7;</code>
       * @param value The groupId to set.
       * @return This builder for chaining.
       */
      public Builder setGroupId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        groupId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 群组ID
       * </pre>
       *
       * <code>string groupId = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearGroupId() {
        
        groupId_ = getDefaultInstance().getGroupId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 群组ID
       * </pre>
       *
       * <code>string groupId = 7;</code>
       * @param value The bytes for groupId to set.
       * @return This builder for chaining.
       */
      public Builder setGroupIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        groupId_ = value;
        onChanged();
        return this;
      }

      private Object extras_ = "";
      /**
       * <pre>
       * 扩展字段,JSON对象格式如：{'扩展字段名称':'扩展字段value'}
       * </pre>
       *
       * <code>string extras = 8;</code>
       * @return The extras.
       */
      public String getExtras() {
        Object ref = extras_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          extras_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 扩展字段,JSON对象格式如：{'扩展字段名称':'扩展字段value'}
       * </pre>
       *
       * <code>string extras = 8;</code>
       * @return The bytes for extras.
       */
      public com.google.protobuf.ByteString
          getExtrasBytes() {
        Object ref = extras_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          extras_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 扩展字段,JSON对象格式如：{'扩展字段名称':'扩展字段value'}
       * </pre>
       *
       * <code>string extras = 8;</code>
       * @param value The extras to set.
       * @return This builder for chaining.
       */
      public Builder setExtras(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        extras_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 扩展字段,JSON对象格式如：{'扩展字段名称':'扩展字段value'}
       * </pre>
       *
       * <code>string extras = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearExtras() {
        
        extras_ = getDefaultInstance().getExtras();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 扩展字段,JSON对象格式如：{'扩展字段名称':'扩展字段value'}
       * </pre>
       *
       * <code>string extras = 8;</code>
       * @param value The bytes for extras to set.
       * @return This builder for chaining.
       */
      public Builder setExtrasBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        extras_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.ChatPacket)
    }

    // @@protoc_insertion_point(class_scope:proto.ChatPacket)
    private static final ChatPacket DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ChatPacket();
    }

    public static ChatPacket getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ChatPacket>
        PARSER = new com.google.protobuf.AbstractParser<ChatPacket>() {
      @Override
      public ChatPacket parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ChatPacket(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ChatPacket> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ChatPacket> getParserForType() {
      return PARSER;
    }

    @Override
    public ChatPacket getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ChatPacket_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_ChatPacket_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020ChatPacket.proto\022\005proto\"\377\002\n\nChatPacket" +
      "\022\016\n\006fromId\030\001 \001(\t\022\014\n\004toId\030\002 \001(\t\022\022\n\ncreate" +
      "Time\030\003 \001(\003\022*\n\007msgType\030\004 \001(\0162\031.proto.Chat" +
      "Packet.MsgType\022,\n\010chatType\030\005 \001(\0162\032.proto" +
      ".ChatPacket.ChatType\022\017\n\007content\030\006 \001(\t\022\017\n" +
      "\007groupId\030\007 \001(\t\022\016\n\006extras\030\010 \001(\t\"\201\001\n\007MsgTy" +
      "pe\022\010\n\004TEXT\020\000\022\t\n\005IMAGE\020\001\022\t\n\005VOICE\020\002\022\t\n\005VI" +
      "DEO\020\003\022\t\n\005MUSIC\020\004\022\010\n\004NEWS\020\005\022\020\n\014ONLINE_VOI" +
      "CE\020\006\022\020\n\014ONLINE_VIDEO\020\007\022\022\n\016ONLINE_MEETING" +
      "\020\010\"/\n\010ChatType\022\013\n\007UNKNOWN\020\000\022\t\n\005GROUP\020\001\022\013" +
      "\n\007PRIVATE\020\002B6\n#cn.starboot.tim.common.pa" +
      "cket.protoB\017ChatPacketProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_proto_ChatPacket_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_ChatPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_ChatPacket_descriptor,
        new String[] { "FromId", "ToId", "CreateTime", "MsgType", "ChatType", "Content", "GroupId", "Extras", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
