// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChatPacket.proto

package cn.starboot.tim.common.packet.proto;

public final class ChatPacketProto {
  private ChatPacketProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ChatPacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ChatPacket)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 发送者ID
     * </pre>
     *
     * <code>string fromId = 1;</code>
     * @return The fromId.
     */
    String getFromId();
    /**
     * <pre>
     * 发送者ID
     * </pre>
     *
     * <code>string fromId = 1;</code>
     * @return The bytes for fromId.
     */
    com.google.protobuf.ByteString
        getFromIdBytes();

    /**
     * <pre>
     * 接收者ID
     * </pre>
     *
     * <code>string toId = 2;</code>
     * @return The toId.
     */
    String getToId();
    /**
     * <pre>
     * 接收者ID
     * </pre>
     *
     * <code>string toId = 2;</code>
     * @return The bytes for toId.
     */
    com.google.protobuf.ByteString
        getToIdBytes();

    /**
     * <pre>
     * 消息创建时间
     * </pre>
     *
     * <code>int64 createTime = 3;</code>
     * @return The createTime.
     */
    long getCreateTime();

    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>.TIMEnum.MsgType msgType = 4;</code>
     * @return The enum numeric value on the wire for msgType.
     */
    int getMsgTypeValue();
    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>.TIMEnum.MsgType msgType = 4;</code>
     * @return The msgType.
     */
    TIMEnumProto.TIMEnum.MsgType getMsgType();

    /**
     * <pre>
     * 聊天类型
     * </pre>
     *
     * <code>.TIMEnum.ChatType chatType = 5;</code>
     * @return The enum numeric value on the wire for chatType.
     */
    int getChatTypeValue();
    /**
     * <pre>
     * 聊天类型
     * </pre>
     *
     * <code>.TIMEnum.ChatType chatType = 5;</code>
     * @return The chatType.
     */
    TIMEnumProto.TIMEnum.ChatType getChatType();

    /**
     * <pre>
     * 消息内容
     * </pre>
     *
     * <code>string content = 6;</code>
     * @return The content.
     */
    String getContent();
    /**
     * <pre>
     * 消息内容
     * </pre>
     *
     * <code>string content = 6;</code>
     * @return The bytes for content.
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <pre>
     * 群组ID
     * </pre>
     *
     * <code>string groupId = 7;</code>
     * @return The groupId.
     */
    String getGroupId();
    /**
     * <pre>
     * 群组ID
     * </pre>
     *
     * <code>string groupId = 7;</code>
     * @return The bytes for groupId.
     */
    com.google.protobuf.ByteString
        getGroupIdBytes();

    /**
     * <pre>
     * 扩展字段,JSON对象格式如：{'扩展字段名称':'扩展字段value'}
     * </pre>
     *
     * <code>string extras = 8;</code>
     * @return The extras.
     */
    String getExtras();
    /**
     * <pre>
     * 扩展字段,JSON对象格式如：{'扩展字段名称':'扩展字段value'}
     * </pre>
     *
     * <code>string extras = 8;</code>
     * @return The bytes for extras.
     */
    com.google.protobuf.ByteString
        getExtrasBytes();
  }
  /**
   * <pre>
   *"from": "来源ID",
   *"to": "目标ID",
   *"createTime": "消息创建时间long类型",
   *"msgType": "消息类型int类型(0:text、1:image、2:voice、3:video、4:music、5:news、6:语音通话、7:视频通话、8:视频会议)",
   *"chatType":"聊天类型int类型(0:未知,1:公聊,2:私聊)",
   *"groupId":"群组id仅在chatType为(1)时需要,String类型",
   *"content": "内容",
   *"extras" : "扩展字段,JSON对象格式如：{'扩展字段名称':'扩展字段value'}"
   * </pre>
   *
   * Protobuf type {@code ChatPacket}
   */
  public static final class ChatPacket extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ChatPacket)
      ChatPacketOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ChatPacket.newBuilder() to construct.
    private ChatPacket(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ChatPacket() {
      fromId_ = "";
      toId_ = "";
      msgType_ = 0;
      chatType_ = 0;
      content_ = "";
      groupId_ = "";
      extras_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new ChatPacket();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ChatPacketProto.internal_static_ChatPacket_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ChatPacketProto.internal_static_ChatPacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ChatPacket.class, Builder.class);
    }

    public static final int FROMID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile Object fromId_ = "";
    /**
     * <pre>
     * 发送者ID
     * </pre>
     *
     * <code>string fromId = 1;</code>
     * @return The fromId.
     */
    @Override
    public String getFromId() {
      Object ref = fromId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        fromId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 发送者ID
     * </pre>
     *
     * <code>string fromId = 1;</code>
     * @return The bytes for fromId.
     */
    @Override
    public com.google.protobuf.ByteString
        getFromIdBytes() {
      Object ref = fromId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        fromId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOID_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile Object toId_ = "";
    /**
     * <pre>
     * 接收者ID
     * </pre>
     *
     * <code>string toId = 2;</code>
     * @return The toId.
     */
    @Override
    public String getToId() {
      Object ref = toId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        toId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 接收者ID
     * </pre>
     *
     * <code>string toId = 2;</code>
     * @return The bytes for toId.
     */
    @Override
    public com.google.protobuf.ByteString
        getToIdBytes() {
      Object ref = toId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        toId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CREATETIME_FIELD_NUMBER = 3;
    private long createTime_ = 0L;
    /**
     * <pre>
     * 消息创建时间
     * </pre>
     *
     * <code>int64 createTime = 3;</code>
     * @return The createTime.
     */
    @Override
    public long getCreateTime() {
      return createTime_;
    }

    public static final int MSGTYPE_FIELD_NUMBER = 4;
    private int msgType_ = 0;
    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>.TIMEnum.MsgType msgType = 4;</code>
     * @return The enum numeric value on the wire for msgType.
     */
    @Override public int getMsgTypeValue() {
      return msgType_;
    }
    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>.TIMEnum.MsgType msgType = 4;</code>
     * @return The msgType.
     */
    @Override public TIMEnumProto.TIMEnum.MsgType getMsgType() {
      TIMEnumProto.TIMEnum.MsgType result = TIMEnumProto.TIMEnum.MsgType.forNumber(msgType_);
      return result == null ? TIMEnumProto.TIMEnum.MsgType.UNRECOGNIZED : result;
    }

    public static final int CHATTYPE_FIELD_NUMBER = 5;
    private int chatType_ = 0;
    /**
     * <pre>
     * 聊天类型
     * </pre>
     *
     * <code>.TIMEnum.ChatType chatType = 5;</code>
     * @return The enum numeric value on the wire for chatType.
     */
    @Override public int getChatTypeValue() {
      return chatType_;
    }
    /**
     * <pre>
     * 聊天类型
     * </pre>
     *
     * <code>.TIMEnum.ChatType chatType = 5;</code>
     * @return The chatType.
     */
    @Override public TIMEnumProto.TIMEnum.ChatType getChatType() {
      TIMEnumProto.TIMEnum.ChatType result = TIMEnumProto.TIMEnum.ChatType.forNumber(chatType_);
      return result == null ? TIMEnumProto.TIMEnum.ChatType.UNRECOGNIZED : result;
    }

    public static final int CONTENT_FIELD_NUMBER = 6;
    @SuppressWarnings("serial")
    private volatile Object content_ = "";
    /**
     * <pre>
     * 消息内容
     * </pre>
     *
     * <code>string content = 6;</code>
     * @return The content.
     */
    @Override
    public String getContent() {
      Object ref = content_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 消息内容
     * </pre>
     *
     * <code>string content = 6;</code>
     * @return The bytes for content.
     */
    @Override
    public com.google.protobuf.ByteString
        getContentBytes() {
      Object ref = content_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GROUPID_FIELD_NUMBER = 7;
    @SuppressWarnings("serial")
    private volatile Object groupId_ = "";
    /**
     * <pre>
     * 群组ID
     * </pre>
     *
     * <code>string groupId = 7;</code>
     * @return The groupId.
     */
    @Override
    public String getGroupId() {
      Object ref = groupId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        groupId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 群组ID
     * </pre>
     *
     * <code>string groupId = 7;</code>
     * @return The bytes for groupId.
     */
    @Override
    public com.google.protobuf.ByteString
        getGroupIdBytes() {
      Object ref = groupId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        groupId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXTRAS_FIELD_NUMBER = 8;
    @SuppressWarnings("serial")
    private volatile Object extras_ = "";
    /**
     * <pre>
     * 扩展字段,JSON对象格式如：{'扩展字段名称':'扩展字段value'}
     * </pre>
     *
     * <code>string extras = 8;</code>
     * @return The extras.
     */
    @Override
    public String getExtras() {
      Object ref = extras_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        extras_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 扩展字段,JSON对象格式如：{'扩展字段名称':'扩展字段value'}
     * </pre>
     *
     * <code>string extras = 8;</code>
     * @return The bytes for extras.
     */
    @Override
    public com.google.protobuf.ByteString
        getExtrasBytes() {
      Object ref = extras_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        extras_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fromId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, fromId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(toId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, toId_);
      }
      if (createTime_ != 0L) {
        output.writeInt64(3, createTime_);
      }
      if (msgType_ != TIMEnumProto.TIMEnum.MsgType.TEXT.getNumber()) {
        output.writeEnum(4, msgType_);
      }
      if (chatType_ != TIMEnumProto.TIMEnum.ChatType.UNKNOWN.getNumber()) {
        output.writeEnum(5, chatType_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(content_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, content_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(groupId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, groupId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(extras_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, extras_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fromId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, fromId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(toId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, toId_);
      }
      if (createTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, createTime_);
      }
      if (msgType_ != TIMEnumProto.TIMEnum.MsgType.TEXT.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, msgType_);
      }
      if (chatType_ != TIMEnumProto.TIMEnum.ChatType.UNKNOWN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, chatType_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(content_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, content_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(groupId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, groupId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(extras_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, extras_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ChatPacket)) {
        return super.equals(obj);
      }
      ChatPacket other = (ChatPacket) obj;

      if (!getFromId()
          .equals(other.getFromId())) return false;
      if (!getToId()
          .equals(other.getToId())) return false;
      if (getCreateTime()
          != other.getCreateTime()) return false;
      if (msgType_ != other.msgType_) return false;
      if (chatType_ != other.chatType_) return false;
      if (!getContent()
          .equals(other.getContent())) return false;
      if (!getGroupId()
          .equals(other.getGroupId())) return false;
      if (!getExtras()
          .equals(other.getExtras())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FROMID_FIELD_NUMBER;
      hash = (53 * hash) + getFromId().hashCode();
      hash = (37 * hash) + TOID_FIELD_NUMBER;
      hash = (53 * hash) + getToId().hashCode();
      hash = (37 * hash) + CREATETIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCreateTime());
      hash = (37 * hash) + MSGTYPE_FIELD_NUMBER;
      hash = (53 * hash) + msgType_;
      hash = (37 * hash) + CHATTYPE_FIELD_NUMBER;
      hash = (53 * hash) + chatType_;
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (37 * hash) + GROUPID_FIELD_NUMBER;
      hash = (53 * hash) + getGroupId().hashCode();
      hash = (37 * hash) + EXTRAS_FIELD_NUMBER;
      hash = (53 * hash) + getExtras().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ChatPacket parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ChatPacket parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ChatPacket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ChatPacket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ChatPacket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ChatPacket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ChatPacket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ChatPacket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ChatPacket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ChatPacket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ChatPacket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ChatPacket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ChatPacket prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *"from": "来源ID",
     *"to": "目标ID",
     *"createTime": "消息创建时间long类型",
     *"msgType": "消息类型int类型(0:text、1:image、2:voice、3:video、4:music、5:news、6:语音通话、7:视频通话、8:视频会议)",
     *"chatType":"聊天类型int类型(0:未知,1:公聊,2:私聊)",
     *"groupId":"群组id仅在chatType为(1)时需要,String类型",
     *"content": "内容",
     *"extras" : "扩展字段,JSON对象格式如：{'扩展字段名称':'扩展字段value'}"
     * </pre>
     *
     * Protobuf type {@code ChatPacket}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ChatPacket)
        ChatPacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ChatPacketProto.internal_static_ChatPacket_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ChatPacketProto.internal_static_ChatPacket_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ChatPacket.class, Builder.class);
      }

      // Construct using cn.starboot.tim.common.packet.proto.ChatPacketProto.ChatPacket.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        fromId_ = "";
        toId_ = "";
        createTime_ = 0L;
        msgType_ = 0;
        chatType_ = 0;
        content_ = "";
        groupId_ = "";
        extras_ = "";
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ChatPacketProto.internal_static_ChatPacket_descriptor;
      }

      @Override
      public ChatPacket getDefaultInstanceForType() {
        return ChatPacket.getDefaultInstance();
      }

      @Override
      public ChatPacket build() {
        ChatPacket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public ChatPacket buildPartial() {
        ChatPacket result = new ChatPacket(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(ChatPacket result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.fromId_ = fromId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.toId_ = toId_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.createTime_ = createTime_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.msgType_ = msgType_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.chatType_ = chatType_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.content_ = content_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.groupId_ = groupId_;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.extras_ = extras_;
        }
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ChatPacket) {
          return mergeFrom((ChatPacket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ChatPacket other) {
        if (other == ChatPacket.getDefaultInstance()) return this;
        if (!other.getFromId().isEmpty()) {
          fromId_ = other.fromId_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getToId().isEmpty()) {
          toId_ = other.toId_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.getCreateTime() != 0L) {
          setCreateTime(other.getCreateTime());
        }
        if (other.msgType_ != 0) {
          setMsgTypeValue(other.getMsgTypeValue());
        }
        if (other.chatType_ != 0) {
          setChatTypeValue(other.getChatTypeValue());
        }
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          bitField0_ |= 0x00000020;
          onChanged();
        }
        if (!other.getGroupId().isEmpty()) {
          groupId_ = other.groupId_;
          bitField0_ |= 0x00000040;
          onChanged();
        }
        if (!other.getExtras().isEmpty()) {
          extras_ = other.extras_;
          bitField0_ |= 0x00000080;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                fromId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                toId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                createTime_ = input.readInt64();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                msgType_ = input.readEnum();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 40: {
                chatType_ = input.readEnum();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              case 50: {
                content_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              case 58: {
                groupId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000040;
                break;
              } // case 58
              case 66: {
                extras_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000080;
                break;
              } // case 66
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private Object fromId_ = "";
      /**
       * <pre>
       * 发送者ID
       * </pre>
       *
       * <code>string fromId = 1;</code>
       * @return The fromId.
       */
      public String getFromId() {
        Object ref = fromId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          fromId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 发送者ID
       * </pre>
       *
       * <code>string fromId = 1;</code>
       * @return The bytes for fromId.
       */
      public com.google.protobuf.ByteString
          getFromIdBytes() {
        Object ref = fromId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          fromId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 发送者ID
       * </pre>
       *
       * <code>string fromId = 1;</code>
       * @param value The fromId to set.
       * @return This builder for chaining.
       */
      public Builder setFromId(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        fromId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 发送者ID
       * </pre>
       *
       * <code>string fromId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFromId() {
        fromId_ = getDefaultInstance().getFromId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 发送者ID
       * </pre>
       *
       * <code>string fromId = 1;</code>
       * @param value The bytes for fromId to set.
       * @return This builder for chaining.
       */
      public Builder setFromIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        fromId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private Object toId_ = "";
      /**
       * <pre>
       * 接收者ID
       * </pre>
       *
       * <code>string toId = 2;</code>
       * @return The toId.
       */
      public String getToId() {
        Object ref = toId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          toId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 接收者ID
       * </pre>
       *
       * <code>string toId = 2;</code>
       * @return The bytes for toId.
       */
      public com.google.protobuf.ByteString
          getToIdBytes() {
        Object ref = toId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          toId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 接收者ID
       * </pre>
       *
       * <code>string toId = 2;</code>
       * @param value The toId to set.
       * @return This builder for chaining.
       */
      public Builder setToId(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        toId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 接收者ID
       * </pre>
       *
       * <code>string toId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearToId() {
        toId_ = getDefaultInstance().getToId();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 接收者ID
       * </pre>
       *
       * <code>string toId = 2;</code>
       * @param value The bytes for toId to set.
       * @return This builder for chaining.
       */
      public Builder setToIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        toId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private long createTime_ ;
      /**
       * <pre>
       * 消息创建时间
       * </pre>
       *
       * <code>int64 createTime = 3;</code>
       * @return The createTime.
       */
      @Override
      public long getCreateTime() {
        return createTime_;
      }
      /**
       * <pre>
       * 消息创建时间
       * </pre>
       *
       * <code>int64 createTime = 3;</code>
       * @param value The createTime to set.
       * @return This builder for chaining.
       */
      public Builder setCreateTime(long value) {

        createTime_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息创建时间
       * </pre>
       *
       * <code>int64 createTime = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearCreateTime() {
        bitField0_ = (bitField0_ & ~0x00000004);
        createTime_ = 0L;
        onChanged();
        return this;
      }

      private int msgType_ = 0;
      /**
       * <pre>
       * 消息类型
       * </pre>
       *
       * <code>.TIMEnum.MsgType msgType = 4;</code>
       * @return The enum numeric value on the wire for msgType.
       */
      @Override public int getMsgTypeValue() {
        return msgType_;
      }
      /**
       * <pre>
       * 消息类型
       * </pre>
       *
       * <code>.TIMEnum.MsgType msgType = 4;</code>
       * @param value The enum numeric value on the wire for msgType to set.
       * @return This builder for chaining.
       */
      public Builder setMsgTypeValue(int value) {
        msgType_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息类型
       * </pre>
       *
       * <code>.TIMEnum.MsgType msgType = 4;</code>
       * @return The msgType.
       */
      @Override
      public TIMEnumProto.TIMEnum.MsgType getMsgType() {
        TIMEnumProto.TIMEnum.MsgType result = TIMEnumProto.TIMEnum.MsgType.forNumber(msgType_);
        return result == null ? TIMEnumProto.TIMEnum.MsgType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * 消息类型
       * </pre>
       *
       * <code>.TIMEnum.MsgType msgType = 4;</code>
       * @param value The msgType to set.
       * @return This builder for chaining.
       */
      public Builder setMsgType(TIMEnumProto.TIMEnum.MsgType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        msgType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息类型
       * </pre>
       *
       * <code>.TIMEnum.MsgType msgType = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgType() {
        bitField0_ = (bitField0_ & ~0x00000008);
        msgType_ = 0;
        onChanged();
        return this;
      }

      private int chatType_ = 0;
      /**
       * <pre>
       * 聊天类型
       * </pre>
       *
       * <code>.TIMEnum.ChatType chatType = 5;</code>
       * @return The enum numeric value on the wire for chatType.
       */
      @Override public int getChatTypeValue() {
        return chatType_;
      }
      /**
       * <pre>
       * 聊天类型
       * </pre>
       *
       * <code>.TIMEnum.ChatType chatType = 5;</code>
       * @param value The enum numeric value on the wire for chatType to set.
       * @return This builder for chaining.
       */
      public Builder setChatTypeValue(int value) {
        chatType_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 聊天类型
       * </pre>
       *
       * <code>.TIMEnum.ChatType chatType = 5;</code>
       * @return The chatType.
       */
      @Override
      public TIMEnumProto.TIMEnum.ChatType getChatType() {
        TIMEnumProto.TIMEnum.ChatType result = TIMEnumProto.TIMEnum.ChatType.forNumber(chatType_);
        return result == null ? TIMEnumProto.TIMEnum.ChatType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * 聊天类型
       * </pre>
       *
       * <code>.TIMEnum.ChatType chatType = 5;</code>
       * @param value The chatType to set.
       * @return This builder for chaining.
       */
      public Builder setChatType(TIMEnumProto.TIMEnum.ChatType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000010;
        chatType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 聊天类型
       * </pre>
       *
       * <code>.TIMEnum.ChatType chatType = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearChatType() {
        bitField0_ = (bitField0_ & ~0x00000010);
        chatType_ = 0;
        onChanged();
        return this;
      }

      private Object content_ = "";
      /**
       * <pre>
       * 消息内容
       * </pre>
       *
       * <code>string content = 6;</code>
       * @return The content.
       */
      public String getContent() {
        Object ref = content_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 消息内容
       * </pre>
       *
       * <code>string content = 6;</code>
       * @return The bytes for content.
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 消息内容
       * </pre>
       *
       * <code>string content = 6;</code>
       * @param value The content to set.
       * @return This builder for chaining.
       */
      public Builder setContent(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        content_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息内容
       * </pre>
       *
       * <code>string content = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearContent() {
        content_ = getDefaultInstance().getContent();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息内容
       * </pre>
       *
       * <code>string content = 6;</code>
       * @param value The bytes for content to set.
       * @return This builder for chaining.
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        content_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }

      private Object groupId_ = "";
      /**
       * <pre>
       * 群组ID
       * </pre>
       *
       * <code>string groupId = 7;</code>
       * @return The groupId.
       */
      public String getGroupId() {
        Object ref = groupId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          groupId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 群组ID
       * </pre>
       *
       * <code>string groupId = 7;</code>
       * @return The bytes for groupId.
       */
      public com.google.protobuf.ByteString
          getGroupIdBytes() {
        Object ref = groupId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          groupId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 群组ID
       * </pre>
       *
       * <code>string groupId = 7;</code>
       * @param value The groupId to set.
       * @return This builder for chaining.
       */
      public Builder setGroupId(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        groupId_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 群组ID
       * </pre>
       *
       * <code>string groupId = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearGroupId() {
        groupId_ = getDefaultInstance().getGroupId();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 群组ID
       * </pre>
       *
       * <code>string groupId = 7;</code>
       * @param value The bytes for groupId to set.
       * @return This builder for chaining.
       */
      public Builder setGroupIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        groupId_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }

      private Object extras_ = "";
      /**
       * <pre>
       * 扩展字段,JSON对象格式如：{'扩展字段名称':'扩展字段value'}
       * </pre>
       *
       * <code>string extras = 8;</code>
       * @return The extras.
       */
      public String getExtras() {
        Object ref = extras_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          extras_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 扩展字段,JSON对象格式如：{'扩展字段名称':'扩展字段value'}
       * </pre>
       *
       * <code>string extras = 8;</code>
       * @return The bytes for extras.
       */
      public com.google.protobuf.ByteString
          getExtrasBytes() {
        Object ref = extras_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          extras_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 扩展字段,JSON对象格式如：{'扩展字段名称':'扩展字段value'}
       * </pre>
       *
       * <code>string extras = 8;</code>
       * @param value The extras to set.
       * @return This builder for chaining.
       */
      public Builder setExtras(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        extras_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 扩展字段,JSON对象格式如：{'扩展字段名称':'扩展字段value'}
       * </pre>
       *
       * <code>string extras = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearExtras() {
        extras_ = getDefaultInstance().getExtras();
        bitField0_ = (bitField0_ & ~0x00000080);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 扩展字段,JSON对象格式如：{'扩展字段名称':'扩展字段value'}
       * </pre>
       *
       * <code>string extras = 8;</code>
       * @param value The bytes for extras to set.
       * @return This builder for chaining.
       */
      public Builder setExtrasBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        extras_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ChatPacket)
    }

    // @@protoc_insertion_point(class_scope:ChatPacket)
    private static final ChatPacket DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ChatPacket();
    }

    public static ChatPacket getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ChatPacket>
        PARSER = new com.google.protobuf.AbstractParser<ChatPacket>() {
      @Override
      public ChatPacket parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ChatPacket> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ChatPacket> getParserForType() {
      return PARSER;
    }

    @Override
    public ChatPacket getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ChatPacket_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ChatPacket_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020ChatPacket.proto\032\rTIMEnum.proto\"\270\001\n\nCh" +
      "atPacket\022\016\n\006fromId\030\001 \001(\t\022\014\n\004toId\030\002 \001(\t\022\022" +
      "\n\ncreateTime\030\003 \001(\003\022!\n\007msgType\030\004 \001(\0162\020.TI" +
      "MEnum.MsgType\022#\n\010chatType\030\005 \001(\0162\021.TIMEnu" +
      "m.ChatType\022\017\n\007content\030\006 \001(\t\022\017\n\007groupId\030\007" +
      " \001(\t\022\016\n\006extras\030\010 \001(\tB6\n#cn.starboot.tim." +
      "common.packet.protoB\017ChatPacketProtob\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          TIMEnumProto.getDescriptor(),
        });
    internal_static_ChatPacket_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ChatPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ChatPacket_descriptor,
        new String[] { "FromId", "ToId", "CreateTime", "MsgType", "ChatType", "Content", "GroupId", "Extras", });
    TIMEnumProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
