// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessagePacket.proto

package cn.starboot.tim.common.packet.proto;

public final class MessagePacketProto {
  private MessagePacketProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessagePacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MessagePacket)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 目标用户ID
     * </pre>
     *
     * <code>string fromUserId = 1;</code>
     * @return The fromUserId.
     */
    String getFromUserId();
    /**
     * <pre>
     * 目标用户ID
     * </pre>
     *
     * <code>string fromUserId = 1;</code>
     * @return The bytes for fromUserId.
     */
    com.google.protobuf.ByteString
        getFromUserIdBytes();

    /**
     * <pre>
     * 当前用户ID
     * </pre>
     *
     * <code>string userId = 2;</code>
     * @return The userId.
     */
    String getUserId();
    /**
     * <pre>
     * 当前用户ID
     * </pre>
     *
     * <code>string userId = 2;</code>
     * @return The bytes for userId.
     */
    com.google.protobuf.ByteString
        getUserIdBytes();

    /**
     * <pre>
     * 群组ID
     * </pre>
     *
     * <code>string groupId = 3;</code>
     * @return The groupId.
     */
    String getGroupId();
    /**
     * <pre>
     * 群组ID
     * </pre>
     *
     * <code>string groupId = 3;</code>
     * @return The bytes for groupId.
     */
    com.google.protobuf.ByteString
        getGroupIdBytes();

    /**
     * <pre>
     * 消息区间开始时间
     * </pre>
     *
     * <code>int64 beginTime = 4;</code>
     * @return The beginTime.
     */
    long getBeginTime();

    /**
     * <pre>
     * 消息区间结束时间
     * </pre>
     *
     * <code>int64 endTime = 5;</code>
     * @return The endTime.
     */
    long getEndTime();

    /**
     * <pre>
     * 分页偏移量
     * </pre>
     *
     * <code>int32 offset = 6;</code>
     * @return The offset.
     */
    int getOffset();

    /**
     * <pre>
     * 显示消息数量
     * </pre>
     *
     * <code>int32 count = 7;</code>
     * @return The count.
     */
    int getCount();

    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>.MessagePacket.MessageType messageType = 8;</code>
     * @return The enum numeric value on the wire for messageType.
     */
    int getMessageTypeValue();
    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>.MessagePacket.MessageType messageType = 8;</code>
     * @return The messageType.
     */
    MessagePacket.MessageType getMessageType();
  }
  /**
   * <pre>
   *"fromUserId":"目标用户id(此字段必须与userId一起使用,获取双方聊天消息),非必填",
   *"userId":"当前用户id(必填字段),当只有此字段时,type必须为0，意思是获取当前用户所有离线消息(好友+群组)",
   *"groupId":"群组id(此字段必须与userId一起使用,获取当前用户指定群组聊天消息),非必填",
   *"beginTime":"消息区间开始时间Date毫秒数double类型,非必填",
   *"endTime":"消息区间结束时间Date毫秒数double类型,非必填",
   *"offset":"分页偏移量int类型，类似Limit 0,10 中的0,非必填",
   *"count":"显示消息数量,类似Limit 0,10 中的10,非必填",
   *"type":"消息类型(0:离线消息,1:历史消息)"
   * </pre>
   *
   * Protobuf type {@code MessagePacket}
   */
  public static final class MessagePacket extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MessagePacket)
      MessagePacketOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MessagePacket.newBuilder() to construct.
    private MessagePacket(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MessagePacket() {
      fromUserId_ = "";
      userId_ = "";
      groupId_ = "";
      messageType_ = 0;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new MessagePacket();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MessagePacket(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              fromUserId_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              userId_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              groupId_ = s;
              break;
            }
            case 32: {

              beginTime_ = input.readInt64();
              break;
            }
            case 40: {

              endTime_ = input.readInt64();
              break;
            }
            case 48: {

              offset_ = input.readInt32();
              break;
            }
            case 56: {

              count_ = input.readInt32();
              break;
            }
            case 64: {
              int rawValue = input.readEnum();

              messageType_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MessagePacketProto.internal_static_MessagePacket_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MessagePacketProto.internal_static_MessagePacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MessagePacket.class, Builder.class);
    }

    /**
     * Protobuf enum {@code MessagePacket.MessageType}
     */
    public enum MessageType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       * 离线消息
       * </pre>
       *
       * <code>OFF_LINE_MESSAGE = 0;</code>
       */
      OFF_LINE_MESSAGE(0),
      /**
       * <pre>
       * 历史消息
       * </pre>
       *
       * <code>HISTORY_MESSAGE = 1;</code>
       */
      HISTORY_MESSAGE(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <pre>
       * 离线消息
       * </pre>
       *
       * <code>OFF_LINE_MESSAGE = 0;</code>
       */
      public static final int OFF_LINE_MESSAGE_VALUE = 0;
      /**
       * <pre>
       * 历史消息
       * </pre>
       *
       * <code>HISTORY_MESSAGE = 1;</code>
       */
      public static final int HISTORY_MESSAGE_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static MessageType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static MessageType forNumber(int value) {
        switch (value) {
          case 0: return OFF_LINE_MESSAGE;
          case 1: return HISTORY_MESSAGE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          MessageType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
              public MessageType findValueByNumber(int number) {
                return MessageType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return MessagePacket.getDescriptor().getEnumTypes().get(0);
      }

      private static final MessageType[] VALUES = values();

      public static MessageType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private MessageType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:MessagePacket.MessageType)
    }

    public static final int FROMUSERID_FIELD_NUMBER = 1;
    private volatile Object fromUserId_;
    /**
     * <pre>
     * 目标用户ID
     * </pre>
     *
     * <code>string fromUserId = 1;</code>
     * @return The fromUserId.
     */
    @Override
    public String getFromUserId() {
      Object ref = fromUserId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        fromUserId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 目标用户ID
     * </pre>
     *
     * <code>string fromUserId = 1;</code>
     * @return The bytes for fromUserId.
     */
    @Override
    public com.google.protobuf.ByteString
        getFromUserIdBytes() {
      Object ref = fromUserId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        fromUserId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERID_FIELD_NUMBER = 2;
    private volatile Object userId_;
    /**
     * <pre>
     * 当前用户ID
     * </pre>
     *
     * <code>string userId = 2;</code>
     * @return The userId.
     */
    @Override
    public String getUserId() {
      Object ref = userId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 当前用户ID
     * </pre>
     *
     * <code>string userId = 2;</code>
     * @return The bytes for userId.
     */
    @Override
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      Object ref = userId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GROUPID_FIELD_NUMBER = 3;
    private volatile Object groupId_;
    /**
     * <pre>
     * 群组ID
     * </pre>
     *
     * <code>string groupId = 3;</code>
     * @return The groupId.
     */
    @Override
    public String getGroupId() {
      Object ref = groupId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        groupId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 群组ID
     * </pre>
     *
     * <code>string groupId = 3;</code>
     * @return The bytes for groupId.
     */
    @Override
    public com.google.protobuf.ByteString
        getGroupIdBytes() {
      Object ref = groupId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        groupId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BEGINTIME_FIELD_NUMBER = 4;
    private long beginTime_;
    /**
     * <pre>
     * 消息区间开始时间
     * </pre>
     *
     * <code>int64 beginTime = 4;</code>
     * @return The beginTime.
     */
    @Override
    public long getBeginTime() {
      return beginTime_;
    }

    public static final int ENDTIME_FIELD_NUMBER = 5;
    private long endTime_;
    /**
     * <pre>
     * 消息区间结束时间
     * </pre>
     *
     * <code>int64 endTime = 5;</code>
     * @return The endTime.
     */
    @Override
    public long getEndTime() {
      return endTime_;
    }

    public static final int OFFSET_FIELD_NUMBER = 6;
    private int offset_;
    /**
     * <pre>
     * 分页偏移量
     * </pre>
     *
     * <code>int32 offset = 6;</code>
     * @return The offset.
     */
    @Override
    public int getOffset() {
      return offset_;
    }

    public static final int COUNT_FIELD_NUMBER = 7;
    private int count_;
    /**
     * <pre>
     * 显示消息数量
     * </pre>
     *
     * <code>int32 count = 7;</code>
     * @return The count.
     */
    @Override
    public int getCount() {
      return count_;
    }

    public static final int MESSAGETYPE_FIELD_NUMBER = 8;
    private int messageType_;
    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>.MessagePacket.MessageType messageType = 8;</code>
     * @return The enum numeric value on the wire for messageType.
     */
    @Override public int getMessageTypeValue() {
      return messageType_;
    }
    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>.MessagePacket.MessageType messageType = 8;</code>
     * @return The messageType.
     */
    @Override public MessageType getMessageType() {
      @SuppressWarnings("deprecation")
      MessageType result = MessageType.valueOf(messageType_);
      return result == null ? MessageType.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fromUserId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, fromUserId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, userId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(groupId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, groupId_);
      }
      if (beginTime_ != 0L) {
        output.writeInt64(4, beginTime_);
      }
      if (endTime_ != 0L) {
        output.writeInt64(5, endTime_);
      }
      if (offset_ != 0) {
        output.writeInt32(6, offset_);
      }
      if (count_ != 0) {
        output.writeInt32(7, count_);
      }
      if (messageType_ != MessageType.OFF_LINE_MESSAGE.getNumber()) {
        output.writeEnum(8, messageType_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fromUserId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, fromUserId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, userId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(groupId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, groupId_);
      }
      if (beginTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, beginTime_);
      }
      if (endTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, endTime_);
      }
      if (offset_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, offset_);
      }
      if (count_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, count_);
      }
      if (messageType_ != MessageType.OFF_LINE_MESSAGE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(8, messageType_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof MessagePacket)) {
        return super.equals(obj);
      }
      MessagePacket other = (MessagePacket) obj;

      if (!getFromUserId()
          .equals(other.getFromUserId())) return false;
      if (!getUserId()
          .equals(other.getUserId())) return false;
      if (!getGroupId()
          .equals(other.getGroupId())) return false;
      if (getBeginTime()
          != other.getBeginTime()) return false;
      if (getEndTime()
          != other.getEndTime()) return false;
      if (getOffset()
          != other.getOffset()) return false;
      if (getCount()
          != other.getCount()) return false;
      if (messageType_ != other.messageType_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FROMUSERID_FIELD_NUMBER;
      hash = (53 * hash) + getFromUserId().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId().hashCode();
      hash = (37 * hash) + GROUPID_FIELD_NUMBER;
      hash = (53 * hash) + getGroupId().hashCode();
      hash = (37 * hash) + BEGINTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getBeginTime());
      hash = (37 * hash) + ENDTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getEndTime());
      hash = (37 * hash) + OFFSET_FIELD_NUMBER;
      hash = (53 * hash) + getOffset();
      hash = (37 * hash) + COUNT_FIELD_NUMBER;
      hash = (53 * hash) + getCount();
      hash = (37 * hash) + MESSAGETYPE_FIELD_NUMBER;
      hash = (53 * hash) + messageType_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static MessagePacket parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MessagePacket parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MessagePacket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MessagePacket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MessagePacket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MessagePacket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MessagePacket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MessagePacket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static MessagePacket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static MessagePacket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static MessagePacket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MessagePacket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MessagePacket prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *"fromUserId":"目标用户id(此字段必须与userId一起使用,获取双方聊天消息),非必填",
     *"userId":"当前用户id(必填字段),当只有此字段时,type必须为0，意思是获取当前用户所有离线消息(好友+群组)",
     *"groupId":"群组id(此字段必须与userId一起使用,获取当前用户指定群组聊天消息),非必填",
     *"beginTime":"消息区间开始时间Date毫秒数double类型,非必填",
     *"endTime":"消息区间结束时间Date毫秒数double类型,非必填",
     *"offset":"分页偏移量int类型，类似Limit 0,10 中的0,非必填",
     *"count":"显示消息数量,类似Limit 0,10 中的10,非必填",
     *"type":"消息类型(0:离线消息,1:历史消息)"
     * </pre>
     *
     * Protobuf type {@code MessagePacket}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MessagePacket)
        MessagePacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MessagePacketProto.internal_static_MessagePacket_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MessagePacketProto.internal_static_MessagePacket_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MessagePacket.class, Builder.class);
      }

      // Construct using cn.starboot.tim.common.packet.proto.MessagePacketProto.MessagePacket.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        fromUserId_ = "";

        userId_ = "";

        groupId_ = "";

        beginTime_ = 0L;

        endTime_ = 0L;

        offset_ = 0;

        count_ = 0;

        messageType_ = 0;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MessagePacketProto.internal_static_MessagePacket_descriptor;
      }

      @Override
      public MessagePacket getDefaultInstanceForType() {
        return MessagePacket.getDefaultInstance();
      }

      @Override
      public MessagePacket build() {
        MessagePacket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public MessagePacket buildPartial() {
        MessagePacket result = new MessagePacket(this);
        result.fromUserId_ = fromUserId_;
        result.userId_ = userId_;
        result.groupId_ = groupId_;
        result.beginTime_ = beginTime_;
        result.endTime_ = endTime_;
        result.offset_ = offset_;
        result.count_ = count_;
        result.messageType_ = messageType_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MessagePacket) {
          return mergeFrom((MessagePacket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MessagePacket other) {
        if (other == MessagePacket.getDefaultInstance()) return this;
        if (!other.getFromUserId().isEmpty()) {
          fromUserId_ = other.fromUserId_;
          onChanged();
        }
        if (!other.getUserId().isEmpty()) {
          userId_ = other.userId_;
          onChanged();
        }
        if (!other.getGroupId().isEmpty()) {
          groupId_ = other.groupId_;
          onChanged();
        }
        if (other.getBeginTime() != 0L) {
          setBeginTime(other.getBeginTime());
        }
        if (other.getEndTime() != 0L) {
          setEndTime(other.getEndTime());
        }
        if (other.getOffset() != 0) {
          setOffset(other.getOffset());
        }
        if (other.getCount() != 0) {
          setCount(other.getCount());
        }
        if (other.messageType_ != 0) {
          setMessageTypeValue(other.getMessageTypeValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        MessagePacket parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (MessagePacket) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object fromUserId_ = "";
      /**
       * <pre>
       * 目标用户ID
       * </pre>
       *
       * <code>string fromUserId = 1;</code>
       * @return The fromUserId.
       */
      public String getFromUserId() {
        Object ref = fromUserId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          fromUserId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 目标用户ID
       * </pre>
       *
       * <code>string fromUserId = 1;</code>
       * @return The bytes for fromUserId.
       */
      public com.google.protobuf.ByteString
          getFromUserIdBytes() {
        Object ref = fromUserId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          fromUserId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 目标用户ID
       * </pre>
       *
       * <code>string fromUserId = 1;</code>
       * @param value The fromUserId to set.
       * @return This builder for chaining.
       */
      public Builder setFromUserId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        fromUserId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 目标用户ID
       * </pre>
       *
       * <code>string fromUserId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFromUserId() {
        
        fromUserId_ = getDefaultInstance().getFromUserId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 目标用户ID
       * </pre>
       *
       * <code>string fromUserId = 1;</code>
       * @param value The bytes for fromUserId to set.
       * @return This builder for chaining.
       */
      public Builder setFromUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        fromUserId_ = value;
        onChanged();
        return this;
      }

      private Object userId_ = "";
      /**
       * <pre>
       * 当前用户ID
       * </pre>
       *
       * <code>string userId = 2;</code>
       * @return The userId.
       */
      public String getUserId() {
        Object ref = userId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          userId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 当前用户ID
       * </pre>
       *
       * <code>string userId = 2;</code>
       * @return The bytes for userId.
       */
      public com.google.protobuf.ByteString
          getUserIdBytes() {
        Object ref = userId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          userId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 当前用户ID
       * </pre>
       *
       * <code>string userId = 2;</code>
       * @param value The userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 当前用户ID
       * </pre>
       *
       * <code>string userId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserId() {
        
        userId_ = getDefaultInstance().getUserId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 当前用户ID
       * </pre>
       *
       * <code>string userId = 2;</code>
       * @param value The bytes for userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userId_ = value;
        onChanged();
        return this;
      }

      private Object groupId_ = "";
      /**
       * <pre>
       * 群组ID
       * </pre>
       *
       * <code>string groupId = 3;</code>
       * @return The groupId.
       */
      public String getGroupId() {
        Object ref = groupId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          groupId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 群组ID
       * </pre>
       *
       * <code>string groupId = 3;</code>
       * @return The bytes for groupId.
       */
      public com.google.protobuf.ByteString
          getGroupIdBytes() {
        Object ref = groupId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          groupId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 群组ID
       * </pre>
       *
       * <code>string groupId = 3;</code>
       * @param value The groupId to set.
       * @return This builder for chaining.
       */
      public Builder setGroupId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        groupId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 群组ID
       * </pre>
       *
       * <code>string groupId = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearGroupId() {
        
        groupId_ = getDefaultInstance().getGroupId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 群组ID
       * </pre>
       *
       * <code>string groupId = 3;</code>
       * @param value The bytes for groupId to set.
       * @return This builder for chaining.
       */
      public Builder setGroupIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        groupId_ = value;
        onChanged();
        return this;
      }

      private long beginTime_ ;
      /**
       * <pre>
       * 消息区间开始时间
       * </pre>
       *
       * <code>int64 beginTime = 4;</code>
       * @return The beginTime.
       */
      @Override
      public long getBeginTime() {
        return beginTime_;
      }
      /**
       * <pre>
       * 消息区间开始时间
       * </pre>
       *
       * <code>int64 beginTime = 4;</code>
       * @param value The beginTime to set.
       * @return This builder for chaining.
       */
      public Builder setBeginTime(long value) {
        
        beginTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息区间开始时间
       * </pre>
       *
       * <code>int64 beginTime = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearBeginTime() {
        
        beginTime_ = 0L;
        onChanged();
        return this;
      }

      private long endTime_ ;
      /**
       * <pre>
       * 消息区间结束时间
       * </pre>
       *
       * <code>int64 endTime = 5;</code>
       * @return The endTime.
       */
      @Override
      public long getEndTime() {
        return endTime_;
      }
      /**
       * <pre>
       * 消息区间结束时间
       * </pre>
       *
       * <code>int64 endTime = 5;</code>
       * @param value The endTime to set.
       * @return This builder for chaining.
       */
      public Builder setEndTime(long value) {
        
        endTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息区间结束时间
       * </pre>
       *
       * <code>int64 endTime = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearEndTime() {
        
        endTime_ = 0L;
        onChanged();
        return this;
      }

      private int offset_ ;
      /**
       * <pre>
       * 分页偏移量
       * </pre>
       *
       * <code>int32 offset = 6;</code>
       * @return The offset.
       */
      @Override
      public int getOffset() {
        return offset_;
      }
      /**
       * <pre>
       * 分页偏移量
       * </pre>
       *
       * <code>int32 offset = 6;</code>
       * @param value The offset to set.
       * @return This builder for chaining.
       */
      public Builder setOffset(int value) {
        
        offset_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 分页偏移量
       * </pre>
       *
       * <code>int32 offset = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearOffset() {
        
        offset_ = 0;
        onChanged();
        return this;
      }

      private int count_ ;
      /**
       * <pre>
       * 显示消息数量
       * </pre>
       *
       * <code>int32 count = 7;</code>
       * @return The count.
       */
      @Override
      public int getCount() {
        return count_;
      }
      /**
       * <pre>
       * 显示消息数量
       * </pre>
       *
       * <code>int32 count = 7;</code>
       * @param value The count to set.
       * @return This builder for chaining.
       */
      public Builder setCount(int value) {
        
        count_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 显示消息数量
       * </pre>
       *
       * <code>int32 count = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearCount() {
        
        count_ = 0;
        onChanged();
        return this;
      }

      private int messageType_ = 0;
      /**
       * <pre>
       * 消息类型
       * </pre>
       *
       * <code>.MessagePacket.MessageType messageType = 8;</code>
       * @return The enum numeric value on the wire for messageType.
       */
      @Override public int getMessageTypeValue() {
        return messageType_;
      }
      /**
       * <pre>
       * 消息类型
       * </pre>
       *
       * <code>.MessagePacket.MessageType messageType = 8;</code>
       * @param value The enum numeric value on the wire for messageType to set.
       * @return This builder for chaining.
       */
      public Builder setMessageTypeValue(int value) {
        
        messageType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息类型
       * </pre>
       *
       * <code>.MessagePacket.MessageType messageType = 8;</code>
       * @return The messageType.
       */
      @Override
      public MessageType getMessageType() {
        @SuppressWarnings("deprecation")
        MessageType result = MessageType.valueOf(messageType_);
        return result == null ? MessageType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * 消息类型
       * </pre>
       *
       * <code>.MessagePacket.MessageType messageType = 8;</code>
       * @param value The messageType to set.
       * @return This builder for chaining.
       */
      public Builder setMessageType(MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        messageType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息类型
       * </pre>
       *
       * <code>.MessagePacket.MessageType messageType = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessageType() {
        
        messageType_ = 0;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MessagePacket)
    }

    // @@protoc_insertion_point(class_scope:MessagePacket)
    private static final MessagePacket DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MessagePacket();
    }

    public static MessagePacket getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MessagePacket>
        PARSER = new com.google.protobuf.AbstractParser<MessagePacket>() {
      @Override
      public MessagePacket parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MessagePacket(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MessagePacket> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<MessagePacket> getParserForType() {
      return PARSER;
    }

    @Override
    public MessagePacket getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MessagePacket_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MessagePacket_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\023MessagePacket.proto\"\362\001\n\rMessagePacket\022" +
      "\022\n\nfromUserId\030\001 \001(\t\022\016\n\006userId\030\002 \001(\t\022\017\n\007g" +
      "roupId\030\003 \001(\t\022\021\n\tbeginTime\030\004 \001(\003\022\017\n\007endTi" +
      "me\030\005 \001(\003\022\016\n\006offset\030\006 \001(\005\022\r\n\005count\030\007 \001(\005\022" +
      "/\n\013messageType\030\010 \001(\0162\032.MessagePacket.Mes" +
      "sageType\"8\n\013MessageType\022\024\n\020OFF_LINE_MESS" +
      "AGE\020\000\022\023\n\017HISTORY_MESSAGE\020\001B9\n#cn.starboo" +
      "t.tim.common.packet.protoB\022MessagePacket" +
      "Protob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_MessagePacket_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MessagePacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MessagePacket_descriptor,
        new String[] { "FromUserId", "UserId", "GroupId", "BeginTime", "EndTime", "Offset", "Count", "MessageType", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
