// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RespPacket.proto

package cn.starboot.tim.common.packet.proto;

public final class RespPacketProto {
  private RespPacketProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RespPacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RespPacket)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.RespPacket.ImStatus imStatus = 1;</code>
     * @return The enum numeric value on the wire for imStatus.
     */
    int getImStatusValue();
    /**
     * <code>.RespPacket.ImStatus imStatus = 1;</code>
     * @return The imStatus.
     */
    RespPacket.ImStatus getImStatus();
  }
  /**
   * <pre>
   * IM私有协议包
   * </pre>
   *
   * Protobuf type {@code RespPacket}
   */
  public static final class RespPacket extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:RespPacket)
      RespPacketOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RespPacket.newBuilder() to construct.
    private RespPacket(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RespPacket() {
      imStatus_ = 0;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new RespPacket();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RespPacketProto.internal_static_RespPacket_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RespPacketProto.internal_static_RespPacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RespPacket.class, Builder.class);
    }

    /**
     * <pre>
     * IM状态响应
     * </pre>
     *
     * Protobuf enum {@code RespPacket.ImStatus}
     */
    public enum ImStatus
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       * TIM status: send success
       * </pre>
       *
       * <code>SEND_FAILED = 0;</code>
       */
      SEND_FAILED(0),
      /**
       * <pre>
       * TIM status: send failed
       * </pre>
       *
       * <code>SEND_SUCCESS = 1;</code>
       */
      SEND_SUCCESS(1),
      /**
       * <pre>
       * TIM status: auth failed
       * </pre>
       *
       * <code>AUTH_FAILED = 2;</code>
       */
      AUTH_FAILED(2),
      /**
       * <pre>
       * TIM status: auth success
       * </pre>
       *
       * <code>AUTH_SUCCESS = 3;</code>
       */
      AUTH_SUCCESS(3),
      /**
       * <pre>
       * TIM status: login failed
       * </pre>
       *
       * <code>LOGIN_FAILED = 4;</code>
       */
      LOGIN_FAILED(4),
      /**
       * <pre>
       * TIM status: login success
       * </pre>
       *
       * <code>LOGIN_SUCCESS = 5;</code>
       */
      LOGIN_SUCCESS(5),
      /**
       * <pre>
       * TIM status: close success
       * </pre>
       *
       * <code>CLOSE_SUCCESS = 6;</code>
       */
      CLOSE_SUCCESS(6),
      /**
       * <pre>
       * TIM status: join group failed
       * </pre>
       *
       * <code>JOIN_GROUP_FAILED = 7;</code>
       */
      JOIN_GROUP_FAILED(7),
      /**
       * <pre>
       * TIM status: join group success
       * </pre>
       *
       * <code>JOIN_GROUP_SUCCESS = 8;</code>
       */
      JOIN_GROUP_SUCCESS(8),
      /**
       * <pre>
       * TIM status: exit group failed
       * </pre>
       *
       * <code>EXIT_GROUP_FAILED = 9;</code>
       */
      EXIT_GROUP_FAILED(9),
      /**
       * <pre>
       * TIM status: exit group success
       * </pre>
       *
       * <code>EXIT_GROUP_SUCCESS = 10;</code>
       */
      EXIT_GROUP_SUCCESS(10),
      /**
       * <pre>
       * TIM status: unsupported cmd command
       * </pre>
       *
       * <code>UNSUPPORTED_CMD_COMMAND = 11;</code>
       */
      UNSUPPORTED_CMD_COMMAND(11),
      /**
       * <pre>
       * TIM status: invalid verification
       * </pre>
       *
       * <code>INVALID_VERIFICATION = 12;</code>
       */
      INVALID_VERIFICATION(12),
      /**
       * <pre>
       * TIM status: get user information failed
       * </pre>
       *
       * <code>GET_USER_INFORMATION_FAILED = 13;</code>
       */
      GET_USER_INFORMATION_FAILED(13),
      /**
       * <pre>
       * TIM status: get user information success
       * </pre>
       *
       * <code>GET_USER_INFORMATION_SUCCESS = 14;</code>
       */
      GET_USER_INFORMATION_SUCCESS(14),
      /**
       * <pre>
       * TIM status: protocol version not match
       * </pre>
       *
       * <code>PROTOCOL_VERSION_NOT_MATCH = 15;</code>
       */
      PROTOCOL_VERSION_NOT_MATCH(15),
      /**
       * <pre>
       * TIM status: get user history message failed
       * </pre>
       *
       * <code>GET_USER_HISTORY_MESSAGE_FAILED = 16;</code>
       */
      GET_USER_HISTORY_MESSAGE_FAILED(16),
      /**
       * <pre>
       * TIM status: get user history message success
       * </pre>
       *
       * <code>GET_USER_HISTORY_MESSAGE_SUCCESS = 17;</code>
       */
      GET_USER_HISTORY_MESSAGE_SUCCESS(17),
      /**
       * <pre>
       * TIM status: get user offline message failed
       * </pre>
       *
       * <code>GET_USER_OFFLINE_MESSAGE_FAILED = 18;</code>
       */
      GET_USER_OFFLINE_MESSAGE_FAILED(18),
      /**
       * <pre>
       * TIM status: get user offline message success
       * </pre>
       *
       * <code>GET_USER_OFFLINE_MESSAGE_SUCCESS = 19;</code>
       */
      GET_USER_OFFLINE_MESSAGE_SUCCESS(19),
      /**
       * <code>C10020 = 20;</code>
       */
      C10020(20),
      /**
       * <code>C10021 = 21;</code>
       */
      C10021(21),
      /**
       * <code>C10022 = 22;</code>
       */
      C10022(22),
      /**
       * <code>C10023 = 23;</code>
       */
      C10023(23),
      /**
       * <code>C10024 = 24;</code>
       */
      C10024(24),
      /**
       * <code>C10025 = 25;</code>
       */
      C10025(25),
      /**
       * <code>C10026 = 26;</code>
       */
      C10026(26),
      /**
       * <code>C10027 = 27;</code>
       */
      C10027(27),
      /**
       * <code>C10028 = 28;</code>
       */
      C10028(28),
      /**
       * <code>C10029 = 29;</code>
       */
      C10029(29),
      UNRECOGNIZED(-1),
      ;

      /**
       * <pre>
       * TIM status: send success
       * </pre>
       *
       * <code>SEND_FAILED = 0;</code>
       */
      public static final int SEND_FAILED_VALUE = 0;
      /**
       * <pre>
       * TIM status: send failed
       * </pre>
       *
       * <code>SEND_SUCCESS = 1;</code>
       */
      public static final int SEND_SUCCESS_VALUE = 1;
      /**
       * <pre>
       * TIM status: auth failed
       * </pre>
       *
       * <code>AUTH_FAILED = 2;</code>
       */
      public static final int AUTH_FAILED_VALUE = 2;
      /**
       * <pre>
       * TIM status: auth success
       * </pre>
       *
       * <code>AUTH_SUCCESS = 3;</code>
       */
      public static final int AUTH_SUCCESS_VALUE = 3;
      /**
       * <pre>
       * TIM status: login failed
       * </pre>
       *
       * <code>LOGIN_FAILED = 4;</code>
       */
      public static final int LOGIN_FAILED_VALUE = 4;
      /**
       * <pre>
       * TIM status: login success
       * </pre>
       *
       * <code>LOGIN_SUCCESS = 5;</code>
       */
      public static final int LOGIN_SUCCESS_VALUE = 5;
      /**
       * <pre>
       * TIM status: close success
       * </pre>
       *
       * <code>CLOSE_SUCCESS = 6;</code>
       */
      public static final int CLOSE_SUCCESS_VALUE = 6;
      /**
       * <pre>
       * TIM status: join group failed
       * </pre>
       *
       * <code>JOIN_GROUP_FAILED = 7;</code>
       */
      public static final int JOIN_GROUP_FAILED_VALUE = 7;
      /**
       * <pre>
       * TIM status: join group success
       * </pre>
       *
       * <code>JOIN_GROUP_SUCCESS = 8;</code>
       */
      public static final int JOIN_GROUP_SUCCESS_VALUE = 8;
      /**
       * <pre>
       * TIM status: exit group failed
       * </pre>
       *
       * <code>EXIT_GROUP_FAILED = 9;</code>
       */
      public static final int EXIT_GROUP_FAILED_VALUE = 9;
      /**
       * <pre>
       * TIM status: exit group success
       * </pre>
       *
       * <code>EXIT_GROUP_SUCCESS = 10;</code>
       */
      public static final int EXIT_GROUP_SUCCESS_VALUE = 10;
      /**
       * <pre>
       * TIM status: unsupported cmd command
       * </pre>
       *
       * <code>UNSUPPORTED_CMD_COMMAND = 11;</code>
       */
      public static final int UNSUPPORTED_CMD_COMMAND_VALUE = 11;
      /**
       * <pre>
       * TIM status: invalid verification
       * </pre>
       *
       * <code>INVALID_VERIFICATION = 12;</code>
       */
      public static final int INVALID_VERIFICATION_VALUE = 12;
      /**
       * <pre>
       * TIM status: get user information failed
       * </pre>
       *
       * <code>GET_USER_INFORMATION_FAILED = 13;</code>
       */
      public static final int GET_USER_INFORMATION_FAILED_VALUE = 13;
      /**
       * <pre>
       * TIM status: get user information success
       * </pre>
       *
       * <code>GET_USER_INFORMATION_SUCCESS = 14;</code>
       */
      public static final int GET_USER_INFORMATION_SUCCESS_VALUE = 14;
      /**
       * <pre>
       * TIM status: protocol version not match
       * </pre>
       *
       * <code>PROTOCOL_VERSION_NOT_MATCH = 15;</code>
       */
      public static final int PROTOCOL_VERSION_NOT_MATCH_VALUE = 15;
      /**
       * <pre>
       * TIM status: get user history message failed
       * </pre>
       *
       * <code>GET_USER_HISTORY_MESSAGE_FAILED = 16;</code>
       */
      public static final int GET_USER_HISTORY_MESSAGE_FAILED_VALUE = 16;
      /**
       * <pre>
       * TIM status: get user history message success
       * </pre>
       *
       * <code>GET_USER_HISTORY_MESSAGE_SUCCESS = 17;</code>
       */
      public static final int GET_USER_HISTORY_MESSAGE_SUCCESS_VALUE = 17;
      /**
       * <pre>
       * TIM status: get user offline message failed
       * </pre>
       *
       * <code>GET_USER_OFFLINE_MESSAGE_FAILED = 18;</code>
       */
      public static final int GET_USER_OFFLINE_MESSAGE_FAILED_VALUE = 18;
      /**
       * <pre>
       * TIM status: get user offline message success
       * </pre>
       *
       * <code>GET_USER_OFFLINE_MESSAGE_SUCCESS = 19;</code>
       */
      public static final int GET_USER_OFFLINE_MESSAGE_SUCCESS_VALUE = 19;
      /**
       * <code>C10020 = 20;</code>
       */
      public static final int C10020_VALUE = 20;
      /**
       * <code>C10021 = 21;</code>
       */
      public static final int C10021_VALUE = 21;
      /**
       * <code>C10022 = 22;</code>
       */
      public static final int C10022_VALUE = 22;
      /**
       * <code>C10023 = 23;</code>
       */
      public static final int C10023_VALUE = 23;
      /**
       * <code>C10024 = 24;</code>
       */
      public static final int C10024_VALUE = 24;
      /**
       * <code>C10025 = 25;</code>
       */
      public static final int C10025_VALUE = 25;
      /**
       * <code>C10026 = 26;</code>
       */
      public static final int C10026_VALUE = 26;
      /**
       * <code>C10027 = 27;</code>
       */
      public static final int C10027_VALUE = 27;
      /**
       * <code>C10028 = 28;</code>
       */
      public static final int C10028_VALUE = 28;
      /**
       * <code>C10029 = 29;</code>
       */
      public static final int C10029_VALUE = 29;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static ImStatus valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static ImStatus forNumber(int value) {
        switch (value) {
          case 0: return SEND_FAILED;
          case 1: return SEND_SUCCESS;
          case 2: return AUTH_FAILED;
          case 3: return AUTH_SUCCESS;
          case 4: return LOGIN_FAILED;
          case 5: return LOGIN_SUCCESS;
          case 6: return CLOSE_SUCCESS;
          case 7: return JOIN_GROUP_FAILED;
          case 8: return JOIN_GROUP_SUCCESS;
          case 9: return EXIT_GROUP_FAILED;
          case 10: return EXIT_GROUP_SUCCESS;
          case 11: return UNSUPPORTED_CMD_COMMAND;
          case 12: return INVALID_VERIFICATION;
          case 13: return GET_USER_INFORMATION_FAILED;
          case 14: return GET_USER_INFORMATION_SUCCESS;
          case 15: return PROTOCOL_VERSION_NOT_MATCH;
          case 16: return GET_USER_HISTORY_MESSAGE_FAILED;
          case 17: return GET_USER_HISTORY_MESSAGE_SUCCESS;
          case 18: return GET_USER_OFFLINE_MESSAGE_FAILED;
          case 19: return GET_USER_OFFLINE_MESSAGE_SUCCESS;
          case 20: return C10020;
          case 21: return C10021;
          case 22: return C10022;
          case 23: return C10023;
          case 24: return C10024;
          case 25: return C10025;
          case 26: return C10026;
          case 27: return C10027;
          case 28: return C10028;
          case 29: return C10029;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ImStatus>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          ImStatus> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ImStatus>() {
              public ImStatus findValueByNumber(int number) {
                return ImStatus.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return RespPacket.getDescriptor().getEnumTypes().get(0);
      }

      private static final ImStatus[] VALUES = values();

      public static ImStatus valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private ImStatus(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:RespPacket.ImStatus)
    }

    public static final int IMSTATUS_FIELD_NUMBER = 1;
    private int imStatus_ = 0;
    /**
     * <code>.RespPacket.ImStatus imStatus = 1;</code>
     * @return The enum numeric value on the wire for imStatus.
     */
    @Override public int getImStatusValue() {
      return imStatus_;
    }
    /**
     * <code>.RespPacket.ImStatus imStatus = 1;</code>
     * @return The imStatus.
     */
    @Override public ImStatus getImStatus() {
      ImStatus result = ImStatus.forNumber(imStatus_);
      return result == null ? ImStatus.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (imStatus_ != ImStatus.SEND_FAILED.getNumber()) {
        output.writeEnum(1, imStatus_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (imStatus_ != ImStatus.SEND_FAILED.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, imStatus_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof RespPacket)) {
        return super.equals(obj);
      }
      RespPacket other = (RespPacket) obj;

      if (imStatus_ != other.imStatus_) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + IMSTATUS_FIELD_NUMBER;
      hash = (53 * hash) + imStatus_;
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static RespPacket parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RespPacket parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RespPacket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RespPacket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RespPacket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RespPacket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RespPacket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RespPacket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static RespPacket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static RespPacket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static RespPacket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RespPacket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(RespPacket prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * IM私有协议包
     * </pre>
     *
     * Protobuf type {@code RespPacket}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RespPacket)
        RespPacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return RespPacketProto.internal_static_RespPacket_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return RespPacketProto.internal_static_RespPacket_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                RespPacket.class, Builder.class);
      }

      // Construct using cn.starboot.tim.common.packet.proto.RespPacketProto.RespPacket.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        imStatus_ = 0;
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return RespPacketProto.internal_static_RespPacket_descriptor;
      }

      @Override
      public RespPacket getDefaultInstanceForType() {
        return RespPacket.getDefaultInstance();
      }

      @Override
      public RespPacket build() {
        RespPacket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public RespPacket buildPartial() {
        RespPacket result = new RespPacket(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(RespPacket result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.imStatus_ = imStatus_;
        }
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof RespPacket) {
          return mergeFrom((RespPacket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(RespPacket other) {
        if (other == RespPacket.getDefaultInstance()) return this;
        if (other.imStatus_ != 0) {
          setImStatusValue(other.getImStatusValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                imStatus_ = input.readEnum();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int imStatus_ = 0;
      /**
       * <code>.RespPacket.ImStatus imStatus = 1;</code>
       * @return The enum numeric value on the wire for imStatus.
       */
      @Override public int getImStatusValue() {
        return imStatus_;
      }
      /**
       * <code>.RespPacket.ImStatus imStatus = 1;</code>
       * @param value The enum numeric value on the wire for imStatus to set.
       * @return This builder for chaining.
       */
      public Builder setImStatusValue(int value) {
        imStatus_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.RespPacket.ImStatus imStatus = 1;</code>
       * @return The imStatus.
       */
      @Override
      public ImStatus getImStatus() {
        ImStatus result = ImStatus.forNumber(imStatus_);
        return result == null ? ImStatus.UNRECOGNIZED : result;
      }
      /**
       * <code>.RespPacket.ImStatus imStatus = 1;</code>
       * @param value The imStatus to set.
       * @return This builder for chaining.
       */
      public Builder setImStatus(ImStatus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        imStatus_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.RespPacket.ImStatus imStatus = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearImStatus() {
        bitField0_ = (bitField0_ & ~0x00000001);
        imStatus_ = 0;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:RespPacket)
    }

    // @@protoc_insertion_point(class_scope:RespPacket)
    private static final RespPacket DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new RespPacket();
    }

    public static RespPacket getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RespPacket>
        PARSER = new com.google.protobuf.AbstractParser<RespPacket>() {
      @Override
      public RespPacket parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<RespPacket> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<RespPacket> getParserForType() {
      return PARSER;
    }

    @Override
    public RespPacket getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RespPacket_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RespPacket_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020RespPacket.proto\"\305\005\n\nRespPacket\022&\n\010imS" +
      "tatus\030\001 \001(\0162\024.RespPacket.ImStatus\"\216\005\n\010Im" +
      "Status\022\017\n\013SEND_FAILED\020\000\022\020\n\014SEND_SUCCESS\020" +
      "\001\022\017\n\013AUTH_FAILED\020\002\022\020\n\014AUTH_SUCCESS\020\003\022\020\n\014" +
      "LOGIN_FAILED\020\004\022\021\n\rLOGIN_SUCCESS\020\005\022\021\n\rCLO" +
      "SE_SUCCESS\020\006\022\025\n\021JOIN_GROUP_FAILED\020\007\022\026\n\022J" +
      "OIN_GROUP_SUCCESS\020\010\022\025\n\021EXIT_GROUP_FAILED" +
      "\020\t\022\026\n\022EXIT_GROUP_SUCCESS\020\n\022\033\n\027UNSUPPORTE" +
      "D_CMD_COMMAND\020\013\022\030\n\024INVALID_VERIFICATION\020" +
      "\014\022\037\n\033GET_USER_INFORMATION_FAILED\020\r\022 \n\034GE" +
      "T_USER_INFORMATION_SUCCESS\020\016\022\036\n\032PROTOCOL" +
      "_VERSION_NOT_MATCH\020\017\022#\n\037GET_USER_HISTORY" +
      "_MESSAGE_FAILED\020\020\022$\n GET_USER_HISTORY_ME" +
      "SSAGE_SUCCESS\020\021\022#\n\037GET_USER_OFFLINE_MESS" +
      "AGE_FAILED\020\022\022$\n GET_USER_OFFLINE_MESSAGE" +
      "_SUCCESS\020\023\022\n\n\006C10020\020\024\022\n\n\006C10021\020\025\022\n\n\006C1" +
      "0022\020\026\022\n\n\006C10023\020\027\022\n\n\006C10024\020\030\022\n\n\006C10025" +
      "\020\031\022\n\n\006C10026\020\032\022\n\n\006C10027\020\033\022\n\n\006C10028\020\034\022\n" +
      "\n\006C10029\020\035B6\n#cn.starboot.tim.common.pac" +
      "ket.protoB\017RespPacketProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_RespPacket_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RespPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RespPacket_descriptor,
        new String[] { "ImStatus", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
