// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RespPacket.proto

package cn.starboot.tim.common.packet.proto;

public final class RespPacketProto {
  private RespPacketProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RespPacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RespPacket)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.RespPacket.ImStatus imStatus = 1;</code>
     * @return The enum numeric value on the wire for imStatus.
     */
    int getImStatusValue();
    /**
     * <code>.RespPacket.ImStatus imStatus = 1;</code>
     * @return The imStatus.
     */
    RespPacket.ImStatus getImStatus();

    /**
     * <code>map&lt;string, string&gt; extra = 2;</code>
     */
    int getExtraCount();
    /**
     * <code>map&lt;string, string&gt; extra = 2;</code>
     */
    boolean containsExtra(
        String key);
    /**
     * Use {@link #getExtraMap()} instead.
     */
    @Deprecated
    java.util.Map<String, String>
    getExtra();
    /**
     * <code>map&lt;string, string&gt; extra = 2;</code>
     */
    java.util.Map<String, String>
    getExtraMap();
    /**
     * <code>map&lt;string, string&gt; extra = 2;</code>
     */
    /* nullable */
String getExtraOrDefault(
        String key,
        /* nullable */
String defaultValue);
    /**
     * <code>map&lt;string, string&gt; extra = 2;</code>
     */
    String getExtraOrThrow(
        String key);
  }
  /**
   * <pre>
   * IM私有协议包
   * </pre>
   *
   * Protobuf type {@code RespPacket}
   */
  public static final class RespPacket extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:RespPacket)
      RespPacketOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RespPacket.newBuilder() to construct.
    private RespPacket(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RespPacket() {
      imStatus_ = 0;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new RespPacket();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RespPacketProto.internal_static_RespPacket_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 2:
          return internalGetExtra();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RespPacketProto.internal_static_RespPacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RespPacket.class, Builder.class);
    }

    /**
     * <pre>
     * IM状态响应
     * </pre>
     *
     * Protobuf enum {@code RespPacket.ImStatus}
     */
    public enum ImStatus
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       * TIM status: default
       * </pre>
       *
       * <code>NONE = 0;</code>
       */
      NONE(0),
      /**
       * <pre>
       * TIM status: send success
       * </pre>
       *
       * <code>SEND_FAILED = 100;</code>
       */
      SEND_FAILED(100),
      /**
       * <pre>
       * TIM status: send failed
       * </pre>
       *
       * <code>SEND_SUCCESS = 101;</code>
       */
      SEND_SUCCESS(101),
      /**
       * <pre>
       * TIM status: auth failed
       * </pre>
       *
       * <code>AUTH_FAILED = 102;</code>
       */
      AUTH_FAILED(102),
      /**
       * <pre>
       * TIM status: auth success
       * </pre>
       *
       * <code>AUTH_SUCCESS = 103;</code>
       */
      AUTH_SUCCESS(103),
      /**
       * <pre>
       * TIM status: login failed
       * </pre>
       *
       * <code>LOGIN_FAILED = 104;</code>
       */
      LOGIN_FAILED(104),
      /**
       * <pre>
       * TIM status: login success
       * </pre>
       *
       * <code>LOGIN_SUCCESS = 105;</code>
       */
      LOGIN_SUCCESS(105),
      /**
       * <pre>
       * TIM status: close success
       * </pre>
       *
       * <code>CLOSE_SUCCESS = 106;</code>
       */
      CLOSE_SUCCESS(106),
      /**
       * <pre>
       * TIM status: join group failed
       * </pre>
       *
       * <code>JOIN_GROUP_FAILED = 107;</code>
       */
      JOIN_GROUP_FAILED(107),
      /**
       * <pre>
       * TIM status: join group success
       * </pre>
       *
       * <code>JOIN_GROUP_SUCCESS = 108;</code>
       */
      JOIN_GROUP_SUCCESS(108),
      /**
       * <pre>
       * TIM status: exit group failed
       * </pre>
       *
       * <code>EXIT_GROUP_FAILED = 109;</code>
       */
      EXIT_GROUP_FAILED(109),
      /**
       * <pre>
       * TIM status: exit group success
       * </pre>
       *
       * <code>EXIT_GROUP_SUCCESS = 110;</code>
       */
      EXIT_GROUP_SUCCESS(110),
      /**
       * <pre>
       * TIM status: unsupported cmd command
       * </pre>
       *
       * <code>UNSUPPORTED_CMD_COMMAND = 111;</code>
       */
      UNSUPPORTED_CMD_COMMAND(111),
      /**
       * <pre>
       * TIM status: invalid verification
       * </pre>
       *
       * <code>INVALID_VERIFICATION = 112;</code>
       */
      INVALID_VERIFICATION(112),
      /**
       * <pre>
       * TIM status: get user information failed
       * </pre>
       *
       * <code>GET_USER_INFORMATION_FAILED = 113;</code>
       */
      GET_USER_INFORMATION_FAILED(113),
      /**
       * <pre>
       * TIM status: get user information success
       * </pre>
       *
       * <code>GET_USER_INFORMATION_SUCCESS = 114;</code>
       */
      GET_USER_INFORMATION_SUCCESS(114),
      /**
       * <pre>
       * TIM status: protocol version not match
       * </pre>
       *
       * <code>PROTOCOL_VERSION_NOT_MATCH = 115;</code>
       */
      PROTOCOL_VERSION_NOT_MATCH(115),
      /**
       * <pre>
       * TIM status: get user history message failed
       * </pre>
       *
       * <code>GET_USER_HISTORY_MESSAGE_FAILED = 116;</code>
       */
      GET_USER_HISTORY_MESSAGE_FAILED(116),
      /**
       * <pre>
       * TIM status: get user history message success
       * </pre>
       *
       * <code>GET_USER_HISTORY_MESSAGE_SUCCESS = 117;</code>
       */
      GET_USER_HISTORY_MESSAGE_SUCCESS(117),
      /**
       * <pre>
       * TIM status: get user offline message failed
       * </pre>
       *
       * <code>GET_USER_OFFLINE_MESSAGE_FAILED = 118;</code>
       */
      GET_USER_OFFLINE_MESSAGE_FAILED(118),
      /**
       * <pre>
       * TIM status: get user offline message success
       * </pre>
       *
       * <code>GET_USER_OFFLINE_MESSAGE_SUCCESS = 119;</code>
       */
      GET_USER_OFFLINE_MESSAGE_SUCCESS(119),
      /**
       * <pre>
       * TIM status: bind failed
       * </pre>
       *
       * <code>BIND_FAILED = 120;</code>
       */
      BIND_FAILED(120),
      /**
       * <pre>
       * TIM status: bind success
       * </pre>
       *
       * <code>BIND_SUCCESS = 121;</code>
       */
      BIND_SUCCESS(121),
      /**
       * <pre>
       * TIM status: unbind failed
       * </pre>
       *
       * <code>UNBIND_FAILED = 122;</code>
       */
      UNBIND_FAILED(122),
      /**
       * <pre>
       * TIM status: unbind success
       * </pre>
       *
       * <code>UNBIND_SUCCESS = 123;</code>
       */
      UNBIND_SUCCESS(123),
      /**
       * <code>C10024 = 124;</code>
       */
      C10024(124),
      /**
       * <code>C10025 = 125;</code>
       */
      C10025(125),
      /**
       * <code>C10026 = 126;</code>
       */
      C10026(126),
      /**
       * <code>C10027 = 127;</code>
       */
      C10027(127),
      /**
       * <code>C10028 = 128;</code>
       */
      C10028(128),
      /**
       * <code>C10029 = 129;</code>
       */
      C10029(129),
      UNRECOGNIZED(-1),
      ;

      /**
       * <pre>
       * TIM status: default
       * </pre>
       *
       * <code>NONE = 0;</code>
       */
      public static final int NONE_VALUE = 0;
      /**
       * <pre>
       * TIM status: send success
       * </pre>
       *
       * <code>SEND_FAILED = 100;</code>
       */
      public static final int SEND_FAILED_VALUE = 100;
      /**
       * <pre>
       * TIM status: send failed
       * </pre>
       *
       * <code>SEND_SUCCESS = 101;</code>
       */
      public static final int SEND_SUCCESS_VALUE = 101;
      /**
       * <pre>
       * TIM status: auth failed
       * </pre>
       *
       * <code>AUTH_FAILED = 102;</code>
       */
      public static final int AUTH_FAILED_VALUE = 102;
      /**
       * <pre>
       * TIM status: auth success
       * </pre>
       *
       * <code>AUTH_SUCCESS = 103;</code>
       */
      public static final int AUTH_SUCCESS_VALUE = 103;
      /**
       * <pre>
       * TIM status: login failed
       * </pre>
       *
       * <code>LOGIN_FAILED = 104;</code>
       */
      public static final int LOGIN_FAILED_VALUE = 104;
      /**
       * <pre>
       * TIM status: login success
       * </pre>
       *
       * <code>LOGIN_SUCCESS = 105;</code>
       */
      public static final int LOGIN_SUCCESS_VALUE = 105;
      /**
       * <pre>
       * TIM status: close success
       * </pre>
       *
       * <code>CLOSE_SUCCESS = 106;</code>
       */
      public static final int CLOSE_SUCCESS_VALUE = 106;
      /**
       * <pre>
       * TIM status: join group failed
       * </pre>
       *
       * <code>JOIN_GROUP_FAILED = 107;</code>
       */
      public static final int JOIN_GROUP_FAILED_VALUE = 107;
      /**
       * <pre>
       * TIM status: join group success
       * </pre>
       *
       * <code>JOIN_GROUP_SUCCESS = 108;</code>
       */
      public static final int JOIN_GROUP_SUCCESS_VALUE = 108;
      /**
       * <pre>
       * TIM status: exit group failed
       * </pre>
       *
       * <code>EXIT_GROUP_FAILED = 109;</code>
       */
      public static final int EXIT_GROUP_FAILED_VALUE = 109;
      /**
       * <pre>
       * TIM status: exit group success
       * </pre>
       *
       * <code>EXIT_GROUP_SUCCESS = 110;</code>
       */
      public static final int EXIT_GROUP_SUCCESS_VALUE = 110;
      /**
       * <pre>
       * TIM status: unsupported cmd command
       * </pre>
       *
       * <code>UNSUPPORTED_CMD_COMMAND = 111;</code>
       */
      public static final int UNSUPPORTED_CMD_COMMAND_VALUE = 111;
      /**
       * <pre>
       * TIM status: invalid verification
       * </pre>
       *
       * <code>INVALID_VERIFICATION = 112;</code>
       */
      public static final int INVALID_VERIFICATION_VALUE = 112;
      /**
       * <pre>
       * TIM status: get user information failed
       * </pre>
       *
       * <code>GET_USER_INFORMATION_FAILED = 113;</code>
       */
      public static final int GET_USER_INFORMATION_FAILED_VALUE = 113;
      /**
       * <pre>
       * TIM status: get user information success
       * </pre>
       *
       * <code>GET_USER_INFORMATION_SUCCESS = 114;</code>
       */
      public static final int GET_USER_INFORMATION_SUCCESS_VALUE = 114;
      /**
       * <pre>
       * TIM status: protocol version not match
       * </pre>
       *
       * <code>PROTOCOL_VERSION_NOT_MATCH = 115;</code>
       */
      public static final int PROTOCOL_VERSION_NOT_MATCH_VALUE = 115;
      /**
       * <pre>
       * TIM status: get user history message failed
       * </pre>
       *
       * <code>GET_USER_HISTORY_MESSAGE_FAILED = 116;</code>
       */
      public static final int GET_USER_HISTORY_MESSAGE_FAILED_VALUE = 116;
      /**
       * <pre>
       * TIM status: get user history message success
       * </pre>
       *
       * <code>GET_USER_HISTORY_MESSAGE_SUCCESS = 117;</code>
       */
      public static final int GET_USER_HISTORY_MESSAGE_SUCCESS_VALUE = 117;
      /**
       * <pre>
       * TIM status: get user offline message failed
       * </pre>
       *
       * <code>GET_USER_OFFLINE_MESSAGE_FAILED = 118;</code>
       */
      public static final int GET_USER_OFFLINE_MESSAGE_FAILED_VALUE = 118;
      /**
       * <pre>
       * TIM status: get user offline message success
       * </pre>
       *
       * <code>GET_USER_OFFLINE_MESSAGE_SUCCESS = 119;</code>
       */
      public static final int GET_USER_OFFLINE_MESSAGE_SUCCESS_VALUE = 119;
      /**
       * <pre>
       * TIM status: bind failed
       * </pre>
       *
       * <code>BIND_FAILED = 120;</code>
       */
      public static final int BIND_FAILED_VALUE = 120;
      /**
       * <pre>
       * TIM status: bind success
       * </pre>
       *
       * <code>BIND_SUCCESS = 121;</code>
       */
      public static final int BIND_SUCCESS_VALUE = 121;
      /**
       * <pre>
       * TIM status: unbind failed
       * </pre>
       *
       * <code>UNBIND_FAILED = 122;</code>
       */
      public static final int UNBIND_FAILED_VALUE = 122;
      /**
       * <pre>
       * TIM status: unbind success
       * </pre>
       *
       * <code>UNBIND_SUCCESS = 123;</code>
       */
      public static final int UNBIND_SUCCESS_VALUE = 123;
      /**
       * <code>C10024 = 124;</code>
       */
      public static final int C10024_VALUE = 124;
      /**
       * <code>C10025 = 125;</code>
       */
      public static final int C10025_VALUE = 125;
      /**
       * <code>C10026 = 126;</code>
       */
      public static final int C10026_VALUE = 126;
      /**
       * <code>C10027 = 127;</code>
       */
      public static final int C10027_VALUE = 127;
      /**
       * <code>C10028 = 128;</code>
       */
      public static final int C10028_VALUE = 128;
      /**
       * <code>C10029 = 129;</code>
       */
      public static final int C10029_VALUE = 129;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static ImStatus valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static ImStatus forNumber(int value) {
        switch (value) {
          case 0: return NONE;
          case 100: return SEND_FAILED;
          case 101: return SEND_SUCCESS;
          case 102: return AUTH_FAILED;
          case 103: return AUTH_SUCCESS;
          case 104: return LOGIN_FAILED;
          case 105: return LOGIN_SUCCESS;
          case 106: return CLOSE_SUCCESS;
          case 107: return JOIN_GROUP_FAILED;
          case 108: return JOIN_GROUP_SUCCESS;
          case 109: return EXIT_GROUP_FAILED;
          case 110: return EXIT_GROUP_SUCCESS;
          case 111: return UNSUPPORTED_CMD_COMMAND;
          case 112: return INVALID_VERIFICATION;
          case 113: return GET_USER_INFORMATION_FAILED;
          case 114: return GET_USER_INFORMATION_SUCCESS;
          case 115: return PROTOCOL_VERSION_NOT_MATCH;
          case 116: return GET_USER_HISTORY_MESSAGE_FAILED;
          case 117: return GET_USER_HISTORY_MESSAGE_SUCCESS;
          case 118: return GET_USER_OFFLINE_MESSAGE_FAILED;
          case 119: return GET_USER_OFFLINE_MESSAGE_SUCCESS;
          case 120: return BIND_FAILED;
          case 121: return BIND_SUCCESS;
          case 122: return UNBIND_FAILED;
          case 123: return UNBIND_SUCCESS;
          case 124: return C10024;
          case 125: return C10025;
          case 126: return C10026;
          case 127: return C10027;
          case 128: return C10028;
          case 129: return C10029;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ImStatus>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          ImStatus> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ImStatus>() {
              public ImStatus findValueByNumber(int number) {
                return ImStatus.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return RespPacket.getDescriptor().getEnumTypes().get(0);
      }

      private static final ImStatus[] VALUES = values();

      public static ImStatus valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private ImStatus(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:RespPacket.ImStatus)
    }

    public static final int IMSTATUS_FIELD_NUMBER = 1;
    private int imStatus_ = 0;
    /**
     * <code>.RespPacket.ImStatus imStatus = 1;</code>
     * @return The enum numeric value on the wire for imStatus.
     */
    @Override public int getImStatusValue() {
      return imStatus_;
    }
    /**
     * <code>.RespPacket.ImStatus imStatus = 1;</code>
     * @return The imStatus.
     */
    @Override public ImStatus getImStatus() {
      ImStatus result = ImStatus.forNumber(imStatus_);
      return result == null ? ImStatus.UNRECOGNIZED : result;
    }

    public static final int EXTRA_FIELD_NUMBER = 2;
    private static final class ExtraDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          String, String> defaultEntry =
              com.google.protobuf.MapEntry
              .<String, String>newDefaultInstance(
                  RespPacketProto.internal_static_RespPacket_ExtraEntry_descriptor,
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    @SuppressWarnings("serial")
    private com.google.protobuf.MapField<
        String, String> extra_;
    private com.google.protobuf.MapField<String, String>
    internalGetExtra() {
      if (extra_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ExtraDefaultEntryHolder.defaultEntry);
      }
      return extra_;
    }
    public int getExtraCount() {
      return internalGetExtra().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; extra = 2;</code>
     */
    @Override
    public boolean containsExtra(
        String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetExtra().getMap().containsKey(key);
    }
    /**
     * Use {@link #getExtraMap()} instead.
     */
    @Override
    @Deprecated
    public java.util.Map<String, String> getExtra() {
      return getExtraMap();
    }
    /**
     * <code>map&lt;string, string&gt; extra = 2;</code>
     */
    @Override
    public java.util.Map<String, String> getExtraMap() {
      return internalGetExtra().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; extra = 2;</code>
     */
    @Override
    public /* nullable */
String getExtraOrDefault(
        String key,
        /* nullable */
String defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<String, String> map =
          internalGetExtra().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; extra = 2;</code>
     */
    @Override
    public String getExtraOrThrow(
        String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<String, String> map =
          internalGetExtra().getMap();
      if (!map.containsKey(key)) {
        throw new IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (imStatus_ != ImStatus.NONE.getNumber()) {
        output.writeEnum(1, imStatus_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetExtra(),
          ExtraDefaultEntryHolder.defaultEntry,
          2);
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (imStatus_ != ImStatus.NONE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, imStatus_);
      }
      for (java.util.Map.Entry<String, String> entry
           : internalGetExtra().getMap().entrySet()) {
        com.google.protobuf.MapEntry<String, String>
        extra__ = ExtraDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, extra__);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof RespPacket)) {
        return super.equals(obj);
      }
      RespPacket other = (RespPacket) obj;

      if (imStatus_ != other.imStatus_) return false;
      if (!internalGetExtra().equals(
          other.internalGetExtra())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + IMSTATUS_FIELD_NUMBER;
      hash = (53 * hash) + imStatus_;
      if (!internalGetExtra().getMap().isEmpty()) {
        hash = (37 * hash) + EXTRA_FIELD_NUMBER;
        hash = (53 * hash) + internalGetExtra().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static RespPacket parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RespPacket parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RespPacket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RespPacket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RespPacket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RespPacket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RespPacket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RespPacket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static RespPacket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static RespPacket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static RespPacket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RespPacket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(RespPacket prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * IM私有协议包
     * </pre>
     *
     * Protobuf type {@code RespPacket}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RespPacket)
        RespPacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return RespPacketProto.internal_static_RespPacket_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 2:
            return internalGetExtra();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 2:
            return internalGetMutableExtra();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return RespPacketProto.internal_static_RespPacket_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                RespPacket.class, Builder.class);
      }

      // Construct using cn.starboot.tim.common.packet.proto.RespPacketProto.RespPacket.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        imStatus_ = 0;
        internalGetMutableExtra().clear();
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return RespPacketProto.internal_static_RespPacket_descriptor;
      }

      @Override
      public RespPacket getDefaultInstanceForType() {
        return RespPacket.getDefaultInstance();
      }

      @Override
      public RespPacket build() {
        RespPacket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public RespPacket buildPartial() {
        RespPacket result = new RespPacket(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(RespPacket result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.imStatus_ = imStatus_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.extra_ = internalGetExtra();
          result.extra_.makeImmutable();
        }
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof RespPacket) {
          return mergeFrom((RespPacket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(RespPacket other) {
        if (other == RespPacket.getDefaultInstance()) return this;
        if (other.imStatus_ != 0) {
          setImStatusValue(other.getImStatusValue());
        }
        internalGetMutableExtra().mergeFrom(
            other.internalGetExtra());
        bitField0_ |= 0x00000002;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                imStatus_ = input.readEnum();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                com.google.protobuf.MapEntry<String, String>
                extra__ = input.readMessage(
                    ExtraDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                internalGetMutableExtra().getMutableMap().put(
                    extra__.getKey(), extra__.getValue());
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int imStatus_ = 0;
      /**
       * <code>.RespPacket.ImStatus imStatus = 1;</code>
       * @return The enum numeric value on the wire for imStatus.
       */
      @Override public int getImStatusValue() {
        return imStatus_;
      }
      /**
       * <code>.RespPacket.ImStatus imStatus = 1;</code>
       * @param value The enum numeric value on the wire for imStatus to set.
       * @return This builder for chaining.
       */
      public Builder setImStatusValue(int value) {
        imStatus_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.RespPacket.ImStatus imStatus = 1;</code>
       * @return The imStatus.
       */
      @Override
      public ImStatus getImStatus() {
        ImStatus result = ImStatus.forNumber(imStatus_);
        return result == null ? ImStatus.UNRECOGNIZED : result;
      }
      /**
       * <code>.RespPacket.ImStatus imStatus = 1;</code>
       * @param value The imStatus to set.
       * @return This builder for chaining.
       */
      public Builder setImStatus(ImStatus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        imStatus_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.RespPacket.ImStatus imStatus = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearImStatus() {
        bitField0_ = (bitField0_ & ~0x00000001);
        imStatus_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          String, String> extra_;
      private com.google.protobuf.MapField<String, String>
          internalGetExtra() {
        if (extra_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              ExtraDefaultEntryHolder.defaultEntry);
        }
        return extra_;
      }
      private com.google.protobuf.MapField<String, String>
          internalGetMutableExtra() {
        if (extra_ == null) {
          extra_ = com.google.protobuf.MapField.newMapField(
              ExtraDefaultEntryHolder.defaultEntry);
        }
        if (!extra_.isMutable()) {
          extra_ = extra_.copy();
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return extra_;
      }
      public int getExtraCount() {
        return internalGetExtra().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; extra = 2;</code>
       */
      @Override
      public boolean containsExtra(
          String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        return internalGetExtra().getMap().containsKey(key);
      }
      /**
       * Use {@link #getExtraMap()} instead.
       */
      @Override
      @Deprecated
      public java.util.Map<String, String> getExtra() {
        return getExtraMap();
      }
      /**
       * <code>map&lt;string, string&gt; extra = 2;</code>
       */
      @Override
      public java.util.Map<String, String> getExtraMap() {
        return internalGetExtra().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; extra = 2;</code>
       */
      @Override
      public /* nullable */
String getExtraOrDefault(
          String key,
          /* nullable */
String defaultValue) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<String, String> map =
            internalGetExtra().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; extra = 2;</code>
       */
      @Override
      public String getExtraOrThrow(
          String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<String, String> map =
            internalGetExtra().getMap();
        if (!map.containsKey(key)) {
          throw new IllegalArgumentException();
        }
        return map.get(key);
      }
      public Builder clearExtra() {
        bitField0_ = (bitField0_ & ~0x00000002);
        internalGetMutableExtra().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; extra = 2;</code>
       */
      public Builder removeExtra(
          String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        internalGetMutableExtra().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @Deprecated
      public java.util.Map<String, String>
          getMutableExtra() {
        bitField0_ |= 0x00000002;
        return internalGetMutableExtra().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; extra = 2;</code>
       */
      public Builder putExtra(
          String key,
          String value) {
        if (key == null) { throw new NullPointerException("map key"); }
        if (value == null) { throw new NullPointerException("map value"); }
        internalGetMutableExtra().getMutableMap()
            .put(key, value);
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; extra = 2;</code>
       */
      public Builder putAllExtra(
          java.util.Map<String, String> values) {
        internalGetMutableExtra().getMutableMap()
            .putAll(values);
        bitField0_ |= 0x00000002;
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:RespPacket)
    }

    // @@protoc_insertion_point(class_scope:RespPacket)
    private static final RespPacket DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new RespPacket();
    }

    public static RespPacket getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RespPacket>
        PARSER = new com.google.protobuf.AbstractParser<RespPacket>() {
      @Override
      public RespPacket parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<RespPacket> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<RespPacket> getParserForType() {
      return PARSER;
    }

    @Override
    public RespPacket getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RespPacket_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RespPacket_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RespPacket_ExtraEntry_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RespPacket_ExtraEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020RespPacket.proto\"\300\006\n\nRespPacket\022&\n\010imS" +
      "tatus\030\001 \001(\0162\024.RespPacket.ImStatus\022%\n\005ext" +
      "ra\030\002 \003(\0132\026.RespPacket.ExtraEntry\032,\n\nExtr" +
      "aEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"\264" +
      "\005\n\010ImStatus\022\010\n\004NONE\020\000\022\017\n\013SEND_FAILED\020d\022\020" +
      "\n\014SEND_SUCCESS\020e\022\017\n\013AUTH_FAILED\020f\022\020\n\014AUT" +
      "H_SUCCESS\020g\022\020\n\014LOGIN_FAILED\020h\022\021\n\rLOGIN_S" +
      "UCCESS\020i\022\021\n\rCLOSE_SUCCESS\020j\022\025\n\021JOIN_GROU" +
      "P_FAILED\020k\022\026\n\022JOIN_GROUP_SUCCESS\020l\022\025\n\021EX" +
      "IT_GROUP_FAILED\020m\022\026\n\022EXIT_GROUP_SUCCESS\020" +
      "n\022\033\n\027UNSUPPORTED_CMD_COMMAND\020o\022\030\n\024INVALI" +
      "D_VERIFICATION\020p\022\037\n\033GET_USER_INFORMATION" +
      "_FAILED\020q\022 \n\034GET_USER_INFORMATION_SUCCES" +
      "S\020r\022\036\n\032PROTOCOL_VERSION_NOT_MATCH\020s\022#\n\037G" +
      "ET_USER_HISTORY_MESSAGE_FAILED\020t\022$\n GET_" +
      "USER_HISTORY_MESSAGE_SUCCESS\020u\022#\n\037GET_US" +
      "ER_OFFLINE_MESSAGE_FAILED\020v\022$\n GET_USER_" +
      "OFFLINE_MESSAGE_SUCCESS\020w\022\017\n\013BIND_FAILED" +
      "\020x\022\020\n\014BIND_SUCCESS\020y\022\021\n\rUNBIND_FAILED\020z\022" +
      "\022\n\016UNBIND_SUCCESS\020{\022\n\n\006C10024\020|\022\n\n\006C1002" +
      "5\020}\022\n\n\006C10026\020~\022\n\n\006C10027\020\177\022\013\n\006C10028\020\200\001" +
      "\022\013\n\006C10029\020\201\001B6\n#cn.starboot.tim.common." +
      "packet.protoB\017RespPacketProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_RespPacket_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RespPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RespPacket_descriptor,
        new String[] { "ImStatus", "Extra", });
    internal_static_RespPacket_ExtraEntry_descriptor =
      internal_static_RespPacket_descriptor.getNestedTypes().get(0);
    internal_static_RespPacket_ExtraEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RespPacket_ExtraEntry_descriptor,
        new String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
