// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RespPacket.proto

package cn.starboot.tim.common.packet.proto;

public final class RespPacketProto {
  private RespPacketProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RespPacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RespPacket)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 是否开启消息同步
     * </pre>
     *
     * <code>bool isSyn = 1;</code>
     * @return The isSyn.
     */
    boolean getIsSyn();

    /**
     * <pre>
     * 同步序列号
     * </pre>
     *
     * <code>string syn = 2;</code>
     * @return The syn.
     */
    String getSyn();
    /**
     * <pre>
     * 同步序列号
     * </pre>
     *
     * <code>string syn = 2;</code>
     * @return The bytes for syn.
     */
    com.google.protobuf.ByteString
        getSynBytes();

    /**
     * <pre>
     * 响应状态码;
     * </pre>
     *
     * <code>int32 code = 3;</code>
     * @return The code.
     */
    int getCode();

    /**
     * <pre>
     * 响应信息;
     * </pre>
     *
     * <code>string msg = 4;</code>
     * @return The msg.
     */
    String getMsg();
    /**
     * <pre>
     * 响应信息;
     * </pre>
     *
     * <code>string msg = 4;</code>
     * @return The bytes for msg.
     */
    com.google.protobuf.ByteString
        getMsgBytes();
  }
  /**
   * <pre>
   * IM私有协议包
   * </pre>
   *
   * Protobuf type {@code RespPacket}
   */
  public static final class RespPacket extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:RespPacket)
      RespPacketOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RespPacket.newBuilder() to construct.
    private RespPacket(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RespPacket() {
      syn_ = "";
      msg_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new RespPacket();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RespPacket(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              isSyn_ = input.readBool();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              syn_ = s;
              break;
            }
            case 24: {

              code_ = input.readInt32();
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              msg_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RespPacketProto.internal_static_RespPacket_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RespPacketProto.internal_static_RespPacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RespPacket.class, Builder.class);
    }

    public static final int ISSYN_FIELD_NUMBER = 1;
    private boolean isSyn_;
    /**
     * <pre>
     * 是否开启消息同步
     * </pre>
     *
     * <code>bool isSyn = 1;</code>
     * @return The isSyn.
     */
    @Override
    public boolean getIsSyn() {
      return isSyn_;
    }

    public static final int SYN_FIELD_NUMBER = 2;
    private volatile Object syn_;
    /**
     * <pre>
     * 同步序列号
     * </pre>
     *
     * <code>string syn = 2;</code>
     * @return The syn.
     */
    @Override
    public String getSyn() {
      Object ref = syn_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        syn_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 同步序列号
     * </pre>
     *
     * <code>string syn = 2;</code>
     * @return The bytes for syn.
     */
    @Override
    public com.google.protobuf.ByteString
        getSynBytes() {
      Object ref = syn_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        syn_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CODE_FIELD_NUMBER = 3;
    private int code_;
    /**
     * <pre>
     * 响应状态码;
     * </pre>
     *
     * <code>int32 code = 3;</code>
     * @return The code.
     */
    @Override
    public int getCode() {
      return code_;
    }

    public static final int MSG_FIELD_NUMBER = 4;
    private volatile Object msg_;
    /**
     * <pre>
     * 响应信息;
     * </pre>
     *
     * <code>string msg = 4;</code>
     * @return The msg.
     */
    @Override
    public String getMsg() {
      Object ref = msg_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        msg_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 响应信息;
     * </pre>
     *
     * <code>string msg = 4;</code>
     * @return The bytes for msg.
     */
    @Override
    public com.google.protobuf.ByteString
        getMsgBytes() {
      Object ref = msg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (isSyn_ != false) {
        output.writeBool(1, isSyn_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(syn_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, syn_);
      }
      if (code_ != 0) {
        output.writeInt32(3, code_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(msg_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, msg_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (isSyn_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, isSyn_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(syn_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, syn_);
      }
      if (code_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, code_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(msg_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, msg_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof RespPacket)) {
        return super.equals(obj);
      }
      RespPacket other = (RespPacket) obj;

      if (getIsSyn()
          != other.getIsSyn()) return false;
      if (!getSyn()
          .equals(other.getSyn())) return false;
      if (getCode()
          != other.getCode()) return false;
      if (!getMsg()
          .equals(other.getMsg())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ISSYN_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsSyn());
      hash = (37 * hash) + SYN_FIELD_NUMBER;
      hash = (53 * hash) + getSyn().hashCode();
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCode();
      hash = (37 * hash) + MSG_FIELD_NUMBER;
      hash = (53 * hash) + getMsg().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static RespPacket parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RespPacket parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RespPacket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RespPacket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RespPacket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RespPacket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RespPacket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RespPacket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static RespPacket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static RespPacket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static RespPacket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RespPacket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(RespPacket prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * IM私有协议包
     * </pre>
     *
     * Protobuf type {@code RespPacket}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RespPacket)
        RespPacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return RespPacketProto.internal_static_RespPacket_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return RespPacketProto.internal_static_RespPacket_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                RespPacket.class, Builder.class);
      }

      // Construct using cn.starboot.tim.common.packet.proto.RespPacketProto.RespPacket.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        isSyn_ = false;

        syn_ = "";

        code_ = 0;

        msg_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return RespPacketProto.internal_static_RespPacket_descriptor;
      }

      @Override
      public RespPacket getDefaultInstanceForType() {
        return RespPacket.getDefaultInstance();
      }

      @Override
      public RespPacket build() {
        RespPacket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public RespPacket buildPartial() {
        RespPacket result = new RespPacket(this);
        result.isSyn_ = isSyn_;
        result.syn_ = syn_;
        result.code_ = code_;
        result.msg_ = msg_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof RespPacket) {
          return mergeFrom((RespPacket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(RespPacket other) {
        if (other == RespPacket.getDefaultInstance()) return this;
        if (other.getIsSyn() != false) {
          setIsSyn(other.getIsSyn());
        }
        if (!other.getSyn().isEmpty()) {
          syn_ = other.syn_;
          onChanged();
        }
        if (other.getCode() != 0) {
          setCode(other.getCode());
        }
        if (!other.getMsg().isEmpty()) {
          msg_ = other.msg_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        RespPacket parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (RespPacket) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean isSyn_ ;
      /**
       * <pre>
       * 是否开启消息同步
       * </pre>
       *
       * <code>bool isSyn = 1;</code>
       * @return The isSyn.
       */
      @Override
      public boolean getIsSyn() {
        return isSyn_;
      }
      /**
       * <pre>
       * 是否开启消息同步
       * </pre>
       *
       * <code>bool isSyn = 1;</code>
       * @param value The isSyn to set.
       * @return This builder for chaining.
       */
      public Builder setIsSyn(boolean value) {
        
        isSyn_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 是否开启消息同步
       * </pre>
       *
       * <code>bool isSyn = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsSyn() {
        
        isSyn_ = false;
        onChanged();
        return this;
      }

      private Object syn_ = "";
      /**
       * <pre>
       * 同步序列号
       * </pre>
       *
       * <code>string syn = 2;</code>
       * @return The syn.
       */
      public String getSyn() {
        Object ref = syn_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          syn_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 同步序列号
       * </pre>
       *
       * <code>string syn = 2;</code>
       * @return The bytes for syn.
       */
      public com.google.protobuf.ByteString
          getSynBytes() {
        Object ref = syn_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          syn_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 同步序列号
       * </pre>
       *
       * <code>string syn = 2;</code>
       * @param value The syn to set.
       * @return This builder for chaining.
       */
      public Builder setSyn(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        syn_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 同步序列号
       * </pre>
       *
       * <code>string syn = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSyn() {
        
        syn_ = getDefaultInstance().getSyn();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 同步序列号
       * </pre>
       *
       * <code>string syn = 2;</code>
       * @param value The bytes for syn to set.
       * @return This builder for chaining.
       */
      public Builder setSynBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        syn_ = value;
        onChanged();
        return this;
      }

      private int code_ ;
      /**
       * <pre>
       * 响应状态码;
       * </pre>
       *
       * <code>int32 code = 3;</code>
       * @return The code.
       */
      @Override
      public int getCode() {
        return code_;
      }
      /**
       * <pre>
       * 响应状态码;
       * </pre>
       *
       * <code>int32 code = 3;</code>
       * @param value The code to set.
       * @return This builder for chaining.
       */
      public Builder setCode(int value) {
        
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 响应状态码;
       * </pre>
       *
       * <code>int32 code = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearCode() {
        
        code_ = 0;
        onChanged();
        return this;
      }

      private Object msg_ = "";
      /**
       * <pre>
       * 响应信息;
       * </pre>
       *
       * <code>string msg = 4;</code>
       * @return The msg.
       */
      public String getMsg() {
        Object ref = msg_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          msg_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 响应信息;
       * </pre>
       *
       * <code>string msg = 4;</code>
       * @return The bytes for msg.
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        Object ref = msg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 响应信息;
       * </pre>
       *
       * <code>string msg = 4;</code>
       * @param value The msg to set.
       * @return This builder for chaining.
       */
      public Builder setMsg(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 响应信息;
       * </pre>
       *
       * <code>string msg = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsg() {
        
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 响应信息;
       * </pre>
       *
       * <code>string msg = 4;</code>
       * @param value The bytes for msg to set.
       * @return This builder for chaining.
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        msg_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:RespPacket)
    }

    // @@protoc_insertion_point(class_scope:RespPacket)
    private static final RespPacket DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new RespPacket();
    }

    public static RespPacket getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RespPacket>
        PARSER = new com.google.protobuf.AbstractParser<RespPacket>() {
      @Override
      public RespPacket parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RespPacket(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RespPacket> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<RespPacket> getParserForType() {
      return PARSER;
    }

    @Override
    public RespPacket getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RespPacket_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RespPacket_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020RespPacket.proto\"C\n\nRespPacket\022\r\n\005isSy" +
      "n\030\001 \001(\010\022\013\n\003syn\030\002 \001(\t\022\014\n\004code\030\003 \001(\005\022\013\n\003ms" +
      "g\030\004 \001(\tB6\n#cn.starboot.tim.common.packet" +
      ".protoB\017RespPacketProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_RespPacket_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RespPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RespPacket_descriptor,
        new String[] { "IsSyn", "Syn", "Code", "Msg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
