// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserPacket.proto

package cn.starboot.tim.common.packet.proto;

public final class UserPacketProto {
  private UserPacketProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UserPacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:UserPacket)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 用户名ID
     * </pre>
     *
     * <code>string userId = 1;</code>
     * @return The userId.
     */
    String getUserId();
    /**
     * <pre>
     * 用户名ID
     * </pre>
     *
     * <code>string userId = 1;</code>
     * @return The bytes for userId.
     */
    com.google.protobuf.ByteString
        getUserIdBytes();

    /**
     * <pre>
     * 好友消息
     * </pre>
     *
     * <code>string nick = 2;</code>
     * @return The nick.
     */
    String getNick();
    /**
     * <pre>
     * 好友消息
     * </pre>
     *
     * <code>string nick = 2;</code>
     * @return The bytes for nick.
     */
    com.google.protobuf.ByteString
        getNickBytes();

    /**
     * <pre>
     * 用户头像
     * </pre>
     *
     * <code>string avatar = 3;</code>
     * @return The avatar.
     */
    String getAvatar();
    /**
     * <pre>
     * 用户头像
     * </pre>
     *
     * <code>string avatar = 3;</code>
     * @return The bytes for avatar.
     */
    com.google.protobuf.ByteString
        getAvatarBytes();

    /**
     * <pre>
     * 用户状态
     * </pre>
     *
     * <code>.TIMEnum.UserStatusType status = 4;</code>
     * @return The enum numeric value on the wire for status.
     */
    int getStatusValue();
    /**
     * <pre>
     * 用户状态
     * </pre>
     *
     * <code>.TIMEnum.UserStatusType status = 4;</code>
     * @return The status.
     */
    TIMEnumProto.TIMEnum.UserStatusType getStatus();

    /**
     * <pre>
     * 个性签名
     * </pre>
     *
     * <code>string sign = 5;</code>
     * @return The sign.
     */
    String getSign();
    /**
     * <pre>
     * 个性签名
     * </pre>
     *
     * <code>string sign = 5;</code>
     * @return The bytes for sign.
     */
    com.google.protobuf.ByteString
        getSignBytes();

    /**
     * <pre>
     * 所属终端
     * </pre>
     *
     * <code>.TIMEnum.Terminal terminal = 6;</code>
     * @return The enum numeric value on the wire for terminal.
     */
    int getTerminalValue();
    /**
     * <pre>
     * 所属终端
     * </pre>
     *
     * <code>.TIMEnum.Terminal terminal = 6;</code>
     * @return The terminal.
     */
    TIMEnumProto.TIMEnum.Terminal getTerminal();

    /**
     * <pre>
     * 好友列表
     * </pre>
     *
     * <code>repeated .UserPacket friends = 7;</code>
     */
    java.util.List<UserPacket>
        getFriendsList();
    /**
     * <pre>
     * 好友列表
     * </pre>
     *
     * <code>repeated .UserPacket friends = 7;</code>
     */
    UserPacket getFriends(int index);
    /**
     * <pre>
     * 好友列表
     * </pre>
     *
     * <code>repeated .UserPacket friends = 7;</code>
     */
    int getFriendsCount();
    /**
     * <pre>
     * 好友列表
     * </pre>
     *
     * <code>repeated .UserPacket friends = 7;</code>
     */
    java.util.List<? extends UserPacketOrBuilder>
        getFriendsOrBuilderList();
    /**
     * <pre>
     * 好友列表
     * </pre>
     *
     * <code>repeated .UserPacket friends = 7;</code>
     */
    UserPacketOrBuilder getFriendsOrBuilder(
        int index);

    /**
     * <pre>
     * 群组列表
     * </pre>
     *
     * <code>repeated string groupId = 8;</code>
     * @return A list containing the groupId.
     */
    java.util.List<String>
        getGroupIdList();
    /**
     * <pre>
     * 群组列表
     * </pre>
     *
     * <code>repeated string groupId = 8;</code>
     * @return The count of groupId.
     */
    int getGroupIdCount();
    /**
     * <pre>
     * 群组列表
     * </pre>
     *
     * <code>repeated string groupId = 8;</code>
     * @param index The index of the element to return.
     * @return The groupId at the given index.
     */
    String getGroupId(int index);
    /**
     * <pre>
     * 群组列表
     * </pre>
     *
     * <code>repeated string groupId = 8;</code>
     * @param index The index of the value to return.
     * @return The bytes of the groupId at the given index.
     */
    com.google.protobuf.ByteString
        getGroupIdBytes(int index);

    /**
     * <pre>
     * 用户昵称拼音
     * </pre>
     *
     * <code>string pinyin = 9;</code>
     * @return The pinyin.
     */
    String getPinyin();
    /**
     * <pre>
     * 用户昵称拼音
     * </pre>
     *
     * <code>string pinyin = 9;</code>
     * @return The bytes for pinyin.
     */
    com.google.protobuf.ByteString
        getPinyinBytes();

    /**
     * <pre>
     * 拼音首字母
     * </pre>
     *
     * <code>string firstLetter = 10;</code>
     * @return The firstLetter.
     */
    String getFirstLetter();
    /**
     * <pre>
     * 拼音首字母
     * </pre>
     *
     * <code>string firstLetter = 10;</code>
     * @return The bytes for firstLetter.
     */
    com.google.protobuf.ByteString
        getFirstLetterBytes();
  }
  /**
   * <pre>
   * IM私有协议包: 用户拉取消息
   * </pre>
   *
   * Protobuf type {@code UserPacket}
   */
  public static final class UserPacket extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:UserPacket)
      UserPacketOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UserPacket.newBuilder() to construct.
    private UserPacket(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UserPacket() {
      userId_ = "";
      nick_ = "";
      avatar_ = "";
      status_ = 0;
      sign_ = "";
      terminal_ = 0;
      friends_ = java.util.Collections.emptyList();
      groupId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      pinyin_ = "";
      firstLetter_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new UserPacket();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return UserPacketProto.internal_static_UserPacket_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return UserPacketProto.internal_static_UserPacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              UserPacket.class, Builder.class);
    }

    public static final int USERID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile Object userId_ = "";
    /**
     * <pre>
     * 用户名ID
     * </pre>
     *
     * <code>string userId = 1;</code>
     * @return The userId.
     */
    @Override
    public String getUserId() {
      Object ref = userId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 用户名ID
     * </pre>
     *
     * <code>string userId = 1;</code>
     * @return The bytes for userId.
     */
    @Override
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      Object ref = userId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NICK_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile Object nick_ = "";
    /**
     * <pre>
     * 好友消息
     * </pre>
     *
     * <code>string nick = 2;</code>
     * @return The nick.
     */
    @Override
    public String getNick() {
      Object ref = nick_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        nick_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 好友消息
     * </pre>
     *
     * <code>string nick = 2;</code>
     * @return The bytes for nick.
     */
    @Override
    public com.google.protobuf.ByteString
        getNickBytes() {
      Object ref = nick_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        nick_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AVATAR_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile Object avatar_ = "";
    /**
     * <pre>
     * 用户头像
     * </pre>
     *
     * <code>string avatar = 3;</code>
     * @return The avatar.
     */
    @Override
    public String getAvatar() {
      Object ref = avatar_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        avatar_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 用户头像
     * </pre>
     *
     * <code>string avatar = 3;</code>
     * @return The bytes for avatar.
     */
    @Override
    public com.google.protobuf.ByteString
        getAvatarBytes() {
      Object ref = avatar_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        avatar_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATUS_FIELD_NUMBER = 4;
    private int status_ = 0;
    /**
     * <pre>
     * 用户状态
     * </pre>
     *
     * <code>.TIMEnum.UserStatusType status = 4;</code>
     * @return The enum numeric value on the wire for status.
     */
    @Override public int getStatusValue() {
      return status_;
    }
    /**
     * <pre>
     * 用户状态
     * </pre>
     *
     * <code>.TIMEnum.UserStatusType status = 4;</code>
     * @return The status.
     */
    @Override public TIMEnumProto.TIMEnum.UserStatusType getStatus() {
      TIMEnumProto.TIMEnum.UserStatusType result = TIMEnumProto.TIMEnum.UserStatusType.forNumber(status_);
      return result == null ? TIMEnumProto.TIMEnum.UserStatusType.UNRECOGNIZED : result;
    }

    public static final int SIGN_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile Object sign_ = "";
    /**
     * <pre>
     * 个性签名
     * </pre>
     *
     * <code>string sign = 5;</code>
     * @return The sign.
     */
    @Override
    public String getSign() {
      Object ref = sign_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        sign_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 个性签名
     * </pre>
     *
     * <code>string sign = 5;</code>
     * @return The bytes for sign.
     */
    @Override
    public com.google.protobuf.ByteString
        getSignBytes() {
      Object ref = sign_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        sign_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TERMINAL_FIELD_NUMBER = 6;
    private int terminal_ = 0;
    /**
     * <pre>
     * 所属终端
     * </pre>
     *
     * <code>.TIMEnum.Terminal terminal = 6;</code>
     * @return The enum numeric value on the wire for terminal.
     */
    @Override public int getTerminalValue() {
      return terminal_;
    }
    /**
     * <pre>
     * 所属终端
     * </pre>
     *
     * <code>.TIMEnum.Terminal terminal = 6;</code>
     * @return The terminal.
     */
    @Override public TIMEnumProto.TIMEnum.Terminal getTerminal() {
      TIMEnumProto.TIMEnum.Terminal result = TIMEnumProto.TIMEnum.Terminal.forNumber(terminal_);
      return result == null ? TIMEnumProto.TIMEnum.Terminal.UNRECOGNIZED : result;
    }

    public static final int FRIENDS_FIELD_NUMBER = 7;
    @SuppressWarnings("serial")
    private java.util.List<UserPacket> friends_;
    /**
     * <pre>
     * 好友列表
     * </pre>
     *
     * <code>repeated .UserPacket friends = 7;</code>
     */
    @Override
    public java.util.List<UserPacket> getFriendsList() {
      return friends_;
    }
    /**
     * <pre>
     * 好友列表
     * </pre>
     *
     * <code>repeated .UserPacket friends = 7;</code>
     */
    @Override
    public java.util.List<? extends UserPacketOrBuilder>
        getFriendsOrBuilderList() {
      return friends_;
    }
    /**
     * <pre>
     * 好友列表
     * </pre>
     *
     * <code>repeated .UserPacket friends = 7;</code>
     */
    @Override
    public int getFriendsCount() {
      return friends_.size();
    }
    /**
     * <pre>
     * 好友列表
     * </pre>
     *
     * <code>repeated .UserPacket friends = 7;</code>
     */
    @Override
    public UserPacket getFriends(int index) {
      return friends_.get(index);
    }
    /**
     * <pre>
     * 好友列表
     * </pre>
     *
     * <code>repeated .UserPacket friends = 7;</code>
     */
    @Override
    public UserPacketOrBuilder getFriendsOrBuilder(
        int index) {
      return friends_.get(index);
    }

    public static final int GROUPID_FIELD_NUMBER = 8;
    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringList groupId_;
    /**
     * <pre>
     * 群组列表
     * </pre>
     *
     * <code>repeated string groupId = 8;</code>
     * @return A list containing the groupId.
     */
    public com.google.protobuf.ProtocolStringList
        getGroupIdList() {
      return groupId_;
    }
    /**
     * <pre>
     * 群组列表
     * </pre>
     *
     * <code>repeated string groupId = 8;</code>
     * @return The count of groupId.
     */
    public int getGroupIdCount() {
      return groupId_.size();
    }
    /**
     * <pre>
     * 群组列表
     * </pre>
     *
     * <code>repeated string groupId = 8;</code>
     * @param index The index of the element to return.
     * @return The groupId at the given index.
     */
    public String getGroupId(int index) {
      return groupId_.get(index);
    }
    /**
     * <pre>
     * 群组列表
     * </pre>
     *
     * <code>repeated string groupId = 8;</code>
     * @param index The index of the value to return.
     * @return The bytes of the groupId at the given index.
     */
    public com.google.protobuf.ByteString
        getGroupIdBytes(int index) {
      return groupId_.getByteString(index);
    }

    public static final int PINYIN_FIELD_NUMBER = 9;
    @SuppressWarnings("serial")
    private volatile Object pinyin_ = "";
    /**
     * <pre>
     * 用户昵称拼音
     * </pre>
     *
     * <code>string pinyin = 9;</code>
     * @return The pinyin.
     */
    @Override
    public String getPinyin() {
      Object ref = pinyin_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        pinyin_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 用户昵称拼音
     * </pre>
     *
     * <code>string pinyin = 9;</code>
     * @return The bytes for pinyin.
     */
    @Override
    public com.google.protobuf.ByteString
        getPinyinBytes() {
      Object ref = pinyin_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        pinyin_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FIRSTLETTER_FIELD_NUMBER = 10;
    @SuppressWarnings("serial")
    private volatile Object firstLetter_ = "";
    /**
     * <pre>
     * 拼音首字母
     * </pre>
     *
     * <code>string firstLetter = 10;</code>
     * @return The firstLetter.
     */
    @Override
    public String getFirstLetter() {
      Object ref = firstLetter_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        firstLetter_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 拼音首字母
     * </pre>
     *
     * <code>string firstLetter = 10;</code>
     * @return The bytes for firstLetter.
     */
    @Override
    public com.google.protobuf.ByteString
        getFirstLetterBytes() {
      Object ref = firstLetter_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        firstLetter_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, userId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(nick_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, nick_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(avatar_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, avatar_);
      }
      if (status_ != TIMEnumProto.TIMEnum.UserStatusType.ONLINE.getNumber()) {
        output.writeEnum(4, status_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sign_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, sign_);
      }
      if (terminal_ != TIMEnumProto.TIMEnum.Terminal.MAC.getNumber()) {
        output.writeEnum(6, terminal_);
      }
      for (int i = 0; i < friends_.size(); i++) {
        output.writeMessage(7, friends_.get(i));
      }
      for (int i = 0; i < groupId_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, groupId_.getRaw(i));
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(pinyin_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, pinyin_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(firstLetter_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, firstLetter_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, userId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(nick_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, nick_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(avatar_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, avatar_);
      }
      if (status_ != TIMEnumProto.TIMEnum.UserStatusType.ONLINE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, status_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sign_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, sign_);
      }
      if (terminal_ != TIMEnumProto.TIMEnum.Terminal.MAC.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(6, terminal_);
      }
      for (int i = 0; i < friends_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, friends_.get(i));
      }
      {
        int dataSize = 0;
        for (int i = 0; i < groupId_.size(); i++) {
          dataSize += computeStringSizeNoTag(groupId_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getGroupIdList().size();
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(pinyin_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, pinyin_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(firstLetter_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, firstLetter_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof UserPacket)) {
        return super.equals(obj);
      }
      UserPacket other = (UserPacket) obj;

      if (!getUserId()
          .equals(other.getUserId())) return false;
      if (!getNick()
          .equals(other.getNick())) return false;
      if (!getAvatar()
          .equals(other.getAvatar())) return false;
      if (status_ != other.status_) return false;
      if (!getSign()
          .equals(other.getSign())) return false;
      if (terminal_ != other.terminal_) return false;
      if (!getFriendsList()
          .equals(other.getFriendsList())) return false;
      if (!getGroupIdList()
          .equals(other.getGroupIdList())) return false;
      if (!getPinyin()
          .equals(other.getPinyin())) return false;
      if (!getFirstLetter()
          .equals(other.getFirstLetter())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId().hashCode();
      hash = (37 * hash) + NICK_FIELD_NUMBER;
      hash = (53 * hash) + getNick().hashCode();
      hash = (37 * hash) + AVATAR_FIELD_NUMBER;
      hash = (53 * hash) + getAvatar().hashCode();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + status_;
      hash = (37 * hash) + SIGN_FIELD_NUMBER;
      hash = (53 * hash) + getSign().hashCode();
      hash = (37 * hash) + TERMINAL_FIELD_NUMBER;
      hash = (53 * hash) + terminal_;
      if (getFriendsCount() > 0) {
        hash = (37 * hash) + FRIENDS_FIELD_NUMBER;
        hash = (53 * hash) + getFriendsList().hashCode();
      }
      if (getGroupIdCount() > 0) {
        hash = (37 * hash) + GROUPID_FIELD_NUMBER;
        hash = (53 * hash) + getGroupIdList().hashCode();
      }
      hash = (37 * hash) + PINYIN_FIELD_NUMBER;
      hash = (53 * hash) + getPinyin().hashCode();
      hash = (37 * hash) + FIRSTLETTER_FIELD_NUMBER;
      hash = (53 * hash) + getFirstLetter().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static UserPacket parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UserPacket parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UserPacket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UserPacket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UserPacket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UserPacket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UserPacket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static UserPacket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static UserPacket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static UserPacket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static UserPacket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static UserPacket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(UserPacket prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * IM私有协议包: 用户拉取消息
     * </pre>
     *
     * Protobuf type {@code UserPacket}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:UserPacket)
        UserPacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return UserPacketProto.internal_static_UserPacket_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return UserPacketProto.internal_static_UserPacket_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                UserPacket.class, Builder.class);
      }

      // Construct using cn.starboot.tim.common.packet.proto.UserPacketProto.UserPacket.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        userId_ = "";
        nick_ = "";
        avatar_ = "";
        status_ = 0;
        sign_ = "";
        terminal_ = 0;
        if (friendsBuilder_ == null) {
          friends_ = java.util.Collections.emptyList();
        } else {
          friends_ = null;
          friendsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000040);
        groupId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000080);
        pinyin_ = "";
        firstLetter_ = "";
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return UserPacketProto.internal_static_UserPacket_descriptor;
      }

      @Override
      public UserPacket getDefaultInstanceForType() {
        return UserPacket.getDefaultInstance();
      }

      @Override
      public UserPacket build() {
        UserPacket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public UserPacket buildPartial() {
        UserPacket result = new UserPacket(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(UserPacket result) {
        if (friendsBuilder_ == null) {
          if (((bitField0_ & 0x00000040) != 0)) {
            friends_ = java.util.Collections.unmodifiableList(friends_);
            bitField0_ = (bitField0_ & ~0x00000040);
          }
          result.friends_ = friends_;
        } else {
          result.friends_ = friendsBuilder_.build();
        }
        if (((bitField0_ & 0x00000080) != 0)) {
          groupId_ = groupId_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000080);
        }
        result.groupId_ = groupId_;
      }

      private void buildPartial0(UserPacket result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.userId_ = userId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.nick_ = nick_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.avatar_ = avatar_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.status_ = status_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.sign_ = sign_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.terminal_ = terminal_;
        }
        if (((from_bitField0_ & 0x00000100) != 0)) {
          result.pinyin_ = pinyin_;
        }
        if (((from_bitField0_ & 0x00000200) != 0)) {
          result.firstLetter_ = firstLetter_;
        }
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof UserPacket) {
          return mergeFrom((UserPacket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(UserPacket other) {
        if (other == UserPacket.getDefaultInstance()) return this;
        if (!other.getUserId().isEmpty()) {
          userId_ = other.userId_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getNick().isEmpty()) {
          nick_ = other.nick_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getAvatar().isEmpty()) {
          avatar_ = other.avatar_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (other.status_ != 0) {
          setStatusValue(other.getStatusValue());
        }
        if (!other.getSign().isEmpty()) {
          sign_ = other.sign_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        if (other.terminal_ != 0) {
          setTerminalValue(other.getTerminalValue());
        }
        if (friendsBuilder_ == null) {
          if (!other.friends_.isEmpty()) {
            if (friends_.isEmpty()) {
              friends_ = other.friends_;
              bitField0_ = (bitField0_ & ~0x00000040);
            } else {
              ensureFriendsIsMutable();
              friends_.addAll(other.friends_);
            }
            onChanged();
          }
        } else {
          if (!other.friends_.isEmpty()) {
            if (friendsBuilder_.isEmpty()) {
              friendsBuilder_.dispose();
              friendsBuilder_ = null;
              friends_ = other.friends_;
              bitField0_ = (bitField0_ & ~0x00000040);
              friendsBuilder_ =
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getFriendsFieldBuilder() : null;
            } else {
              friendsBuilder_.addAllMessages(other.friends_);
            }
          }
        }
        if (!other.groupId_.isEmpty()) {
          if (groupId_.isEmpty()) {
            groupId_ = other.groupId_;
            bitField0_ = (bitField0_ & ~0x00000080);
          } else {
            ensureGroupIdIsMutable();
            groupId_.addAll(other.groupId_);
          }
          onChanged();
        }
        if (!other.getPinyin().isEmpty()) {
          pinyin_ = other.pinyin_;
          bitField0_ |= 0x00000100;
          onChanged();
        }
        if (!other.getFirstLetter().isEmpty()) {
          firstLetter_ = other.firstLetter_;
          bitField0_ |= 0x00000200;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                userId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                nick_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                avatar_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 32: {
                status_ = input.readEnum();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 42: {
                sign_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              case 48: {
                terminal_ = input.readEnum();
                bitField0_ |= 0x00000020;
                break;
              } // case 48
              case 58: {
                UserPacket m =
                    input.readMessage(
                        UserPacket.parser(),
                        extensionRegistry);
                if (friendsBuilder_ == null) {
                  ensureFriendsIsMutable();
                  friends_.add(m);
                } else {
                  friendsBuilder_.addMessage(m);
                }
                break;
              } // case 58
              case 66: {
                String s = input.readStringRequireUtf8();
                ensureGroupIdIsMutable();
                groupId_.add(s);
                break;
              } // case 66
              case 74: {
                pinyin_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000100;
                break;
              } // case 74
              case 82: {
                firstLetter_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000200;
                break;
              } // case 82
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private Object userId_ = "";
      /**
       * <pre>
       * 用户名ID
       * </pre>
       *
       * <code>string userId = 1;</code>
       * @return The userId.
       */
      public String getUserId() {
        Object ref = userId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          userId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 用户名ID
       * </pre>
       *
       * <code>string userId = 1;</code>
       * @return The bytes for userId.
       */
      public com.google.protobuf.ByteString
          getUserIdBytes() {
        Object ref = userId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          userId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 用户名ID
       * </pre>
       *
       * <code>string userId = 1;</code>
       * @param value The userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserId(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        userId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 用户名ID
       * </pre>
       *
       * <code>string userId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserId() {
        userId_ = getDefaultInstance().getUserId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 用户名ID
       * </pre>
       *
       * <code>string userId = 1;</code>
       * @param value The bytes for userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        userId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private Object nick_ = "";
      /**
       * <pre>
       * 好友消息
       * </pre>
       *
       * <code>string nick = 2;</code>
       * @return The nick.
       */
      public String getNick() {
        Object ref = nick_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          nick_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 好友消息
       * </pre>
       *
       * <code>string nick = 2;</code>
       * @return The bytes for nick.
       */
      public com.google.protobuf.ByteString
          getNickBytes() {
        Object ref = nick_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          nick_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 好友消息
       * </pre>
       *
       * <code>string nick = 2;</code>
       * @param value The nick to set.
       * @return This builder for chaining.
       */
      public Builder setNick(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        nick_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 好友消息
       * </pre>
       *
       * <code>string nick = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearNick() {
        nick_ = getDefaultInstance().getNick();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 好友消息
       * </pre>
       *
       * <code>string nick = 2;</code>
       * @param value The bytes for nick to set.
       * @return This builder for chaining.
       */
      public Builder setNickBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        nick_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private Object avatar_ = "";
      /**
       * <pre>
       * 用户头像
       * </pre>
       *
       * <code>string avatar = 3;</code>
       * @return The avatar.
       */
      public String getAvatar() {
        Object ref = avatar_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          avatar_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 用户头像
       * </pre>
       *
       * <code>string avatar = 3;</code>
       * @return The bytes for avatar.
       */
      public com.google.protobuf.ByteString
          getAvatarBytes() {
        Object ref = avatar_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          avatar_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 用户头像
       * </pre>
       *
       * <code>string avatar = 3;</code>
       * @param value The avatar to set.
       * @return This builder for chaining.
       */
      public Builder setAvatar(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        avatar_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 用户头像
       * </pre>
       *
       * <code>string avatar = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearAvatar() {
        avatar_ = getDefaultInstance().getAvatar();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 用户头像
       * </pre>
       *
       * <code>string avatar = 3;</code>
       * @param value The bytes for avatar to set.
       * @return This builder for chaining.
       */
      public Builder setAvatarBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        avatar_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private int status_ = 0;
      /**
       * <pre>
       * 用户状态
       * </pre>
       *
       * <code>.TIMEnum.UserStatusType status = 4;</code>
       * @return The enum numeric value on the wire for status.
       */
      @Override public int getStatusValue() {
        return status_;
      }
      /**
       * <pre>
       * 用户状态
       * </pre>
       *
       * <code>.TIMEnum.UserStatusType status = 4;</code>
       * @param value The enum numeric value on the wire for status to set.
       * @return This builder for chaining.
       */
      public Builder setStatusValue(int value) {
        status_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 用户状态
       * </pre>
       *
       * <code>.TIMEnum.UserStatusType status = 4;</code>
       * @return The status.
       */
      @Override
      public TIMEnumProto.TIMEnum.UserStatusType getStatus() {
        TIMEnumProto.TIMEnum.UserStatusType result = TIMEnumProto.TIMEnum.UserStatusType.forNumber(status_);
        return result == null ? TIMEnumProto.TIMEnum.UserStatusType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * 用户状态
       * </pre>
       *
       * <code>.TIMEnum.UserStatusType status = 4;</code>
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(TIMEnumProto.TIMEnum.UserStatusType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        status_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 用户状态
       * </pre>
       *
       * <code>.TIMEnum.UserStatusType status = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000008);
        status_ = 0;
        onChanged();
        return this;
      }

      private Object sign_ = "";
      /**
       * <pre>
       * 个性签名
       * </pre>
       *
       * <code>string sign = 5;</code>
       * @return The sign.
       */
      public String getSign() {
        Object ref = sign_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          sign_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 个性签名
       * </pre>
       *
       * <code>string sign = 5;</code>
       * @return The bytes for sign.
       */
      public com.google.protobuf.ByteString
          getSignBytes() {
        Object ref = sign_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          sign_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 个性签名
       * </pre>
       *
       * <code>string sign = 5;</code>
       * @param value The sign to set.
       * @return This builder for chaining.
       */
      public Builder setSign(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        sign_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 个性签名
       * </pre>
       *
       * <code>string sign = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearSign() {
        sign_ = getDefaultInstance().getSign();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 个性签名
       * </pre>
       *
       * <code>string sign = 5;</code>
       * @param value The bytes for sign to set.
       * @return This builder for chaining.
       */
      public Builder setSignBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        sign_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      private int terminal_ = 0;
      /**
       * <pre>
       * 所属终端
       * </pre>
       *
       * <code>.TIMEnum.Terminal terminal = 6;</code>
       * @return The enum numeric value on the wire for terminal.
       */
      @Override public int getTerminalValue() {
        return terminal_;
      }
      /**
       * <pre>
       * 所属终端
       * </pre>
       *
       * <code>.TIMEnum.Terminal terminal = 6;</code>
       * @param value The enum numeric value on the wire for terminal to set.
       * @return This builder for chaining.
       */
      public Builder setTerminalValue(int value) {
        terminal_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 所属终端
       * </pre>
       *
       * <code>.TIMEnum.Terminal terminal = 6;</code>
       * @return The terminal.
       */
      @Override
      public TIMEnumProto.TIMEnum.Terminal getTerminal() {
        TIMEnumProto.TIMEnum.Terminal result = TIMEnumProto.TIMEnum.Terminal.forNumber(terminal_);
        return result == null ? TIMEnumProto.TIMEnum.Terminal.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * 所属终端
       * </pre>
       *
       * <code>.TIMEnum.Terminal terminal = 6;</code>
       * @param value The terminal to set.
       * @return This builder for chaining.
       */
      public Builder setTerminal(TIMEnumProto.TIMEnum.Terminal value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000020;
        terminal_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 所属终端
       * </pre>
       *
       * <code>.TIMEnum.Terminal terminal = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearTerminal() {
        bitField0_ = (bitField0_ & ~0x00000020);
        terminal_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<UserPacket> friends_ =
        java.util.Collections.emptyList();
      private void ensureFriendsIsMutable() {
        if (!((bitField0_ & 0x00000040) != 0)) {
          friends_ = new java.util.ArrayList<UserPacket>(friends_);
          bitField0_ |= 0x00000040;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          UserPacket, Builder, UserPacketOrBuilder> friendsBuilder_;

      /**
       * <pre>
       * 好友列表
       * </pre>
       *
       * <code>repeated .UserPacket friends = 7;</code>
       */
      public java.util.List<UserPacket> getFriendsList() {
        if (friendsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(friends_);
        } else {
          return friendsBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * 好友列表
       * </pre>
       *
       * <code>repeated .UserPacket friends = 7;</code>
       */
      public int getFriendsCount() {
        if (friendsBuilder_ == null) {
          return friends_.size();
        } else {
          return friendsBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * 好友列表
       * </pre>
       *
       * <code>repeated .UserPacket friends = 7;</code>
       */
      public UserPacket getFriends(int index) {
        if (friendsBuilder_ == null) {
          return friends_.get(index);
        } else {
          return friendsBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * 好友列表
       * </pre>
       *
       * <code>repeated .UserPacket friends = 7;</code>
       */
      public Builder setFriends(
          int index, UserPacket value) {
        if (friendsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFriendsIsMutable();
          friends_.set(index, value);
          onChanged();
        } else {
          friendsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 好友列表
       * </pre>
       *
       * <code>repeated .UserPacket friends = 7;</code>
       */
      public Builder setFriends(
          int index, Builder builderForValue) {
        if (friendsBuilder_ == null) {
          ensureFriendsIsMutable();
          friends_.set(index, builderForValue.build());
          onChanged();
        } else {
          friendsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 好友列表
       * </pre>
       *
       * <code>repeated .UserPacket friends = 7;</code>
       */
      public Builder addFriends(UserPacket value) {
        if (friendsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFriendsIsMutable();
          friends_.add(value);
          onChanged();
        } else {
          friendsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * 好友列表
       * </pre>
       *
       * <code>repeated .UserPacket friends = 7;</code>
       */
      public Builder addFriends(
          int index, UserPacket value) {
        if (friendsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFriendsIsMutable();
          friends_.add(index, value);
          onChanged();
        } else {
          friendsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 好友列表
       * </pre>
       *
       * <code>repeated .UserPacket friends = 7;</code>
       */
      public Builder addFriends(
          Builder builderForValue) {
        if (friendsBuilder_ == null) {
          ensureFriendsIsMutable();
          friends_.add(builderForValue.build());
          onChanged();
        } else {
          friendsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 好友列表
       * </pre>
       *
       * <code>repeated .UserPacket friends = 7;</code>
       */
      public Builder addFriends(
          int index, Builder builderForValue) {
        if (friendsBuilder_ == null) {
          ensureFriendsIsMutable();
          friends_.add(index, builderForValue.build());
          onChanged();
        } else {
          friendsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 好友列表
       * </pre>
       *
       * <code>repeated .UserPacket friends = 7;</code>
       */
      public Builder addAllFriends(
          Iterable<? extends UserPacket> values) {
        if (friendsBuilder_ == null) {
          ensureFriendsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, friends_);
          onChanged();
        } else {
          friendsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * 好友列表
       * </pre>
       *
       * <code>repeated .UserPacket friends = 7;</code>
       */
      public Builder clearFriends() {
        if (friendsBuilder_ == null) {
          friends_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000040);
          onChanged();
        } else {
          friendsBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * 好友列表
       * </pre>
       *
       * <code>repeated .UserPacket friends = 7;</code>
       */
      public Builder removeFriends(int index) {
        if (friendsBuilder_ == null) {
          ensureFriendsIsMutable();
          friends_.remove(index);
          onChanged();
        } else {
          friendsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * 好友列表
       * </pre>
       *
       * <code>repeated .UserPacket friends = 7;</code>
       */
      public Builder getFriendsBuilder(
          int index) {
        return getFriendsFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * 好友列表
       * </pre>
       *
       * <code>repeated .UserPacket friends = 7;</code>
       */
      public UserPacketOrBuilder getFriendsOrBuilder(
          int index) {
        if (friendsBuilder_ == null) {
          return friends_.get(index);  } else {
          return friendsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * 好友列表
       * </pre>
       *
       * <code>repeated .UserPacket friends = 7;</code>
       */
      public java.util.List<? extends UserPacketOrBuilder>
           getFriendsOrBuilderList() {
        if (friendsBuilder_ != null) {
          return friendsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(friends_);
        }
      }
      /**
       * <pre>
       * 好友列表
       * </pre>
       *
       * <code>repeated .UserPacket friends = 7;</code>
       */
      public Builder addFriendsBuilder() {
        return getFriendsFieldBuilder().addBuilder(
            UserPacket.getDefaultInstance());
      }
      /**
       * <pre>
       * 好友列表
       * </pre>
       *
       * <code>repeated .UserPacket friends = 7;</code>
       */
      public Builder addFriendsBuilder(
          int index) {
        return getFriendsFieldBuilder().addBuilder(
            index, UserPacket.getDefaultInstance());
      }
      /**
       * <pre>
       * 好友列表
       * </pre>
       *
       * <code>repeated .UserPacket friends = 7;</code>
       */
      public java.util.List<Builder>
           getFriendsBuilderList() {
        return getFriendsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          UserPacket, Builder, UserPacketOrBuilder>
          getFriendsFieldBuilder() {
        if (friendsBuilder_ == null) {
          friendsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              UserPacket, Builder, UserPacketOrBuilder>(
                  friends_,
                  ((bitField0_ & 0x00000040) != 0),
                  getParentForChildren(),
                  isClean());
          friends_ = null;
        }
        return friendsBuilder_;
      }

      private com.google.protobuf.LazyStringList groupId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureGroupIdIsMutable() {
        if (!((bitField0_ & 0x00000080) != 0)) {
          groupId_ = new com.google.protobuf.LazyStringArrayList(groupId_);
          bitField0_ |= 0x00000080;
         }
      }
      /**
       * <pre>
       * 群组列表
       * </pre>
       *
       * <code>repeated string groupId = 8;</code>
       * @return A list containing the groupId.
       */
      public com.google.protobuf.ProtocolStringList
          getGroupIdList() {
        return groupId_.getUnmodifiableView();
      }
      /**
       * <pre>
       * 群组列表
       * </pre>
       *
       * <code>repeated string groupId = 8;</code>
       * @return The count of groupId.
       */
      public int getGroupIdCount() {
        return groupId_.size();
      }
      /**
       * <pre>
       * 群组列表
       * </pre>
       *
       * <code>repeated string groupId = 8;</code>
       * @param index The index of the element to return.
       * @return The groupId at the given index.
       */
      public String getGroupId(int index) {
        return groupId_.get(index);
      }
      /**
       * <pre>
       * 群组列表
       * </pre>
       *
       * <code>repeated string groupId = 8;</code>
       * @param index The index of the value to return.
       * @return The bytes of the groupId at the given index.
       */
      public com.google.protobuf.ByteString
          getGroupIdBytes(int index) {
        return groupId_.getByteString(index);
      }
      /**
       * <pre>
       * 群组列表
       * </pre>
       *
       * <code>repeated string groupId = 8;</code>
       * @param index The index to set the value at.
       * @param value The groupId to set.
       * @return This builder for chaining.
       */
      public Builder setGroupId(
          int index, String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureGroupIdIsMutable();
        groupId_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 群组列表
       * </pre>
       *
       * <code>repeated string groupId = 8;</code>
       * @param value The groupId to add.
       * @return This builder for chaining.
       */
      public Builder addGroupId(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureGroupIdIsMutable();
        groupId_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 群组列表
       * </pre>
       *
       * <code>repeated string groupId = 8;</code>
       * @param values The groupId to add.
       * @return This builder for chaining.
       */
      public Builder addAllGroupId(
          Iterable<String> values) {
        ensureGroupIdIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, groupId_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 群组列表
       * </pre>
       *
       * <code>repeated string groupId = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearGroupId() {
        groupId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000080);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 群组列表
       * </pre>
       *
       * <code>repeated string groupId = 8;</code>
       * @param value The bytes of the groupId to add.
       * @return This builder for chaining.
       */
      public Builder addGroupIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ensureGroupIdIsMutable();
        groupId_.add(value);
        onChanged();
        return this;
      }

      private Object pinyin_ = "";
      /**
       * <pre>
       * 用户昵称拼音
       * </pre>
       *
       * <code>string pinyin = 9;</code>
       * @return The pinyin.
       */
      public String getPinyin() {
        Object ref = pinyin_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          pinyin_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 用户昵称拼音
       * </pre>
       *
       * <code>string pinyin = 9;</code>
       * @return The bytes for pinyin.
       */
      public com.google.protobuf.ByteString
          getPinyinBytes() {
        Object ref = pinyin_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          pinyin_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 用户昵称拼音
       * </pre>
       *
       * <code>string pinyin = 9;</code>
       * @param value The pinyin to set.
       * @return This builder for chaining.
       */
      public Builder setPinyin(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        pinyin_ = value;
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 用户昵称拼音
       * </pre>
       *
       * <code>string pinyin = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearPinyin() {
        pinyin_ = getDefaultInstance().getPinyin();
        bitField0_ = (bitField0_ & ~0x00000100);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 用户昵称拼音
       * </pre>
       *
       * <code>string pinyin = 9;</code>
       * @param value The bytes for pinyin to set.
       * @return This builder for chaining.
       */
      public Builder setPinyinBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        pinyin_ = value;
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }

      private Object firstLetter_ = "";
      /**
       * <pre>
       * 拼音首字母
       * </pre>
       *
       * <code>string firstLetter = 10;</code>
       * @return The firstLetter.
       */
      public String getFirstLetter() {
        Object ref = firstLetter_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          firstLetter_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 拼音首字母
       * </pre>
       *
       * <code>string firstLetter = 10;</code>
       * @return The bytes for firstLetter.
       */
      public com.google.protobuf.ByteString
          getFirstLetterBytes() {
        Object ref = firstLetter_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          firstLetter_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 拼音首字母
       * </pre>
       *
       * <code>string firstLetter = 10;</code>
       * @param value The firstLetter to set.
       * @return This builder for chaining.
       */
      public Builder setFirstLetter(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        firstLetter_ = value;
        bitField0_ |= 0x00000200;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 拼音首字母
       * </pre>
       *
       * <code>string firstLetter = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearFirstLetter() {
        firstLetter_ = getDefaultInstance().getFirstLetter();
        bitField0_ = (bitField0_ & ~0x00000200);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 拼音首字母
       * </pre>
       *
       * <code>string firstLetter = 10;</code>
       * @param value The bytes for firstLetter to set.
       * @return This builder for chaining.
       */
      public Builder setFirstLetterBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        firstLetter_ = value;
        bitField0_ |= 0x00000200;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:UserPacket)
    }

    // @@protoc_insertion_point(class_scope:UserPacket)
    private static final UserPacket DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new UserPacket();
    }

    public static UserPacket getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserPacket>
        PARSER = new com.google.protobuf.AbstractParser<UserPacket>() {
      @Override
      public UserPacket parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<UserPacket> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<UserPacket> getParserForType() {
      return PARSER;
    }

    @Override
    public UserPacket getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserPacket_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserPacket_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020UserPacket.proto\032\rTIMEnum.proto\"\352\001\n\nUs" +
      "erPacket\022\016\n\006userId\030\001 \001(\t\022\014\n\004nick\030\002 \001(\t\022\016" +
      "\n\006avatar\030\003 \001(\t\022\'\n\006status\030\004 \001(\0162\027.TIMEnum" +
      ".UserStatusType\022\014\n\004sign\030\005 \001(\t\022#\n\010termina" +
      "l\030\006 \001(\0162\021.TIMEnum.Terminal\022\034\n\007friends\030\007 " +
      "\003(\0132\013.UserPacket\022\017\n\007groupId\030\010 \003(\t\022\016\n\006pin" +
      "yin\030\t \001(\t\022\023\n\013firstLetter\030\n \001(\tB6\n#cn.sta" +
      "rboot.tim.common.packet.protoB\017UserPacke" +
      "tProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          TIMEnumProto.getDescriptor(),
        });
    internal_static_UserPacket_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_UserPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserPacket_descriptor,
        new String[] { "UserId", "Nick", "Avatar", "Status", "Sign", "Terminal", "Friends", "GroupId", "Pinyin", "FirstLetter", });
    TIMEnumProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
